package br.tcc.Interface;

import br.tcc.Validacoes.LimparCampos;
import br.tcc.Validacoes.PreencherJtableGenerico;
import br.tcc.Validacoes.RetornaDataAtual;
import br.tcc.classe.Cidade;
import br.tcc.classe.Cliente;
import br.tcc.classe.Endereco;
import br.tcc.classe.Pessoa;
import br.tcc.classe.PessoaFisica;
import br.tcc.classe.PessoaJuridica;
import br.tcc.classe.Telefone;
import br.tcc.dao.CidadeDAO;
import br.tcc.dao.ClienteDAO;
import br.tcc.dao.EnderecoDAO;
import br.tcc.dao.PessoaDAO;
import br.tcc.dao.PessoaFisicaDAO;
import br.tcc.dao.PessoaJuridicaDAO;
import br.tcc.dao.TelefoneDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Joao Paulo
 */
public class InterfaceCliente extends javax.swing.JFrame {

    LimparCampos lcampos = new LimparCampos();
    private int situacao = 0;
    CidadeDAO cidadeDAO = new CidadeDAO();
    RetornaDataAtual retornadata = new RetornaDataAtual();
    Cidade cidade = new Cidade();
    PessoaFisicaDAO pfDao = new PessoaFisicaDAO();
    PessoaJuridicaDAO pjDao = new PessoaJuridicaDAO();
    EnderecoDAO endDao = new EnderecoDAO();
    PessoaFisica pfisica = new PessoaFisica();
    PessoaJuridica pjuridica = new PessoaJuridica();
    Endereco endereco = new Endereco();
    Pessoa pessoa = new Pessoa();
    PessoaDAO pessoaDao = new PessoaDAO();
    Integer dig1, dig2, dig3, dig4, dig5, dig6, dig7, dig8, dig9, dig10, dig11;
    Integer dig21, dig22, dig23, dig24, dig25, dig26, dig27, dig28, dig29, dig210, dig211;
    Telefone telefone = new Telefone();
    TelefoneDAO telefoneDAO = new TelefoneDAO();
    Cliente cliente = new Cliente();
    ClienteDAO clienteDAO = new ClienteDAO();

    /**
     * Creates new form InterfacePessoa
     */
    public InterfaceCliente() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGtipo_pessoa = new javax.swing.ButtonGroup();
        jTPcliente = new javax.swing.JTabbedPane();
        jPCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFIdPessoa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFnome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRBFisico = new javax.swing.JRadioButton();
        jRBJuridica = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCBCidade = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTFlogradouro = new javax.swing.JTextField();
        jTFNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFbairro = new javax.swing.JTextField();
        jTFcomplemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFNrCep = new javax.swing.JFormattedTextField();
        jPpfisica = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Sexo = new javax.swing.JLabel();
        jCBSexo = new javax.swing.JComboBox();
        jTFNrCpf = new javax.swing.JFormattedTextField();
        jTFrg = new javax.swing.JFormattedTextField();
        jPpjuridica = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFrazaosocial = new javax.swing.JTextField();
        jTFcnpj = new javax.swing.JFormattedTextField();
        jPanelbotoes = new javax.swing.JPanel();
        jBIncluir = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBgravar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBAlterar1 = new javax.swing.JButton();
        BaddPessoas = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jTFdtnasc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTFDtCadastro = new javax.swing.JTextField();
        jBPesquisar2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jCBSituacao = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jTFFone1 = new javax.swing.JFormattedTextField();
        jPConsulta1 = new javax.swing.JPanel();
        jCbPesquisa1 = new javax.swing.JComboBox();
        jTFPesquisa1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbPesquisa1 = new javax.swing.JTable();
        jBtPesquisa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jLabel1.setText("Código");

        jLabel9.setText("Nome");

        jLabel10.setText("Data de cadastro");

        bGtipo_pessoa.add(jRBFisico);
        jRBFisico.setText("Física");
        jRBFisico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBFisicoMouseClicked(evt);
            }
        });
        jRBFisico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jRBFisicoKeyTyped(evt);
            }
        });

        bGtipo_pessoa.add(jRBJuridica);
        jRBJuridica.setText("Juridica");
        jRBJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBJuridicaMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel2.setText("Cidade");

        jLabel3.setText("Logradouro");

        jLabel4.setText("Número");

        jLabel6.setText("Complemento");

        jLabel5.setText("Bairro");

        jLabel7.setText("CEP");

        try {
            jTFNrCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel7))
                            .addComponent(jTFNrCep, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTFlogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 135, Short.MAX_VALUE))
                            .addComponent(jTFbairro))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTFcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(175, 175, 175))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFlogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNrCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPpfisica.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Física"));

        jLabel11.setText("CPF");

        jLabel12.setText("RG");

        Sexo.setText("Sexo");

        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FEMININO", "MASCULINO" }));

        try {
            jTFNrCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTFNrCpf.setText("");
        jTFNrCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNrCpfFocusLost(evt);
            }
        });

        try {
            jTFrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.### #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPpfisicaLayout = new javax.swing.GroupLayout(jPpfisica);
        jPpfisica.setLayout(jPpfisicaLayout);
        jPpfisicaLayout.setHorizontalGroup(
            jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpfisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPpfisicaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel12))
                    .addGroup(jPpfisicaLayout.createSequentialGroup()
                        .addComponent(jTFNrCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFrg, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sexo)
                    .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPpfisicaLayout.setVerticalGroup(
            jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpfisicaLayout.createSequentialGroup()
                .addComponent(Sexo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPpfisicaLayout.createSequentialGroup()
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNrCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPpjuridica.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Juridica"));

        jLabel14.setText("CNPJ");

        jLabel16.setText("Razão Social");

        try {
            jTFcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTFcnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFcnpjFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPpjuridicaLayout = new javax.swing.GroupLayout(jPpjuridica);
        jPpjuridica.setLayout(jPpjuridicaLayout);
        jPpjuridicaLayout.setHorizontalGroup(
            jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpjuridicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpjuridicaLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPpjuridicaLayout.createSequentialGroup()
                        .addComponent(jTFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)))
        );
        jPpjuridicaLayout.setVerticalGroup(
            jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpjuridicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelbotoes.setBackground(new java.awt.Color(153, 153, 153));

        jBIncluir.setText("Incluir");
        jBIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncluirActionPerformed(evt);
            }
        });

        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBgravar.setText("Gravar");
        jBgravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgravarActionPerformed(evt);
            }
        });

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBAlterar1.setText("Alterar");
        jBAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbotoesLayout = new javax.swing.GroupLayout(jPanelbotoes);
        jPanelbotoes.setLayout(jPanelbotoesLayout);
        jPanelbotoesLayout.setHorizontalGroup(
            jPanelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotoesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jBIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jBAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jBgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jBcancelar)
                .addGap(35, 35, 35))
        );
        jPanelbotoesLayout.setVerticalGroup(
            jPanelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotoesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        BaddPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tcc/fotos/addPessoa.jpg"))); // NOI18N
        BaddPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaddPessoasActionPerformed(evt);
            }
        });

        jLabel13.setText("Data de Nascimento");

        jLabel18.setText("Tipo de Pessoa");

        jBPesquisar2.setText("Pesquisar");
        jBPesquisar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisar2MouseClicked(evt);
            }
        });
        jBPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisar2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Situação");

        jCBSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        jLabel24.setText("Telefone");

        try {
            jTFFone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addComponent(jPanelbotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(151, 151, 151)
                                .addComponent(jLabel9))
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBPesquisar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel18))
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addComponent(jRBFisico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBJuridica)))
                                .addGap(4, 4, 4)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jTFFone1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jTFdtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCBSituacao, 0, 96, Short.MAX_VALUE)
                                    .addGap(91, 91, 91)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                                .addComponent(BaddPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addComponent(jPpfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPpjuridica, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPesquisar2)
                            .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFdtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(26, 26, 26)))
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BaddPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRBJuridica)
                                    .addComponent(jRBFisico)
                                    .addComponent(jTFFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPpfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPpjuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelbotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTPcliente.addTab("Cadastro", jPCadastro);

        jCbPesquisa1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Cliente" }));
        jCbPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbPesquisa1ActionPerformed(evt);
            }
        });

        jTbPesquisa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Data de Cadastro", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbPesquisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbPesquisa1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTbPesquisa1);

        jBtPesquisa1.setText("Pesquisar");
        jBtPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPConsulta1Layout = new javax.swing.GroupLayout(jPConsulta1);
        jPConsulta1.setLayout(jPConsulta1Layout);
        jPConsulta1Layout.setHorizontalGroup(
            jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsulta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPConsulta1Layout.createSequentialGroup()
                        .addComponent(jCbPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisa1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPConsulta1Layout.setVerticalGroup(
            jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsulta1Layout.createSequentialGroup()
                .addGroup(jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPConsulta1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtPesquisa1)
                            .addComponent(jTFPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPConsulta1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jCbPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPcliente.addTab("Consulta", jPConsulta1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTPcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPcliente, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(776, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPesquisar2ActionPerformed

    private void jBPesquisar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisar2MouseClicked
        final InterfaceRetornaPessoa retornaPessoa = new InterfaceRetornaPessoa();
        retornaPessoa.setVisible(true);
        retornaPessoa.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdPessoa.setText(retornaPessoa.retornaId);
                jTFnome.setText(retornaPessoa.retornaDsPessoa);
                jTFdtnasc.setText(retornaPessoa.retornaDtNasc);
            }
        });

    }//GEN-LAST:event_jBPesquisar2MouseClicked

    private void BaddPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaddPessoasActionPerformed

        InterfaceRelacaoPessoa InRelPesso = new InterfaceRelacaoPessoa();

        if (jTFIdPessoa.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Para adicionar uma pessoa ao grupo de amigos é necessario preencher dados do cliente!");
        } else {
            try {
                InRelPesso.CapturaIdPessoa(jTFIdPessoa.getText());
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if (!jTFnome.getText().equals("")) {
            try {
                InRelPesso.capturaDsPessoa(jTFnome.getText());
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceFuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
            InRelPesso.setVisible(true);
        }
    }//GEN-LAST:event_BaddPessoasActionPerformed

    private void jBAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterar1ActionPerformed
        situacao = 2;
        estadobotoes(true);
    }//GEN-LAST:event_jBAlterar1ActionPerformed

    private void jBgravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgravarActionPerformed
        Integer idCidade = null;
        if (situacao == 1) {
            if (jTFIdPessoa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Cliente");
                jTFIdPessoa.grabFocus();
                return;
            } else {
                cliente.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
            }

            cliente.setDTCADASTRO(jTFDtCadastro.getText());
            cliente.setTPSITUACAO(jCBSituacao.getSelectedIndex());

            telefone.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            if (jTFFone1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o número do Telefone");
                jTFFone1.grabFocus();
                return;
            } else {
                telefone.setNRFONE(jTFFone1.getText());

            }
            telefone.setTPFONE("Recado");

            if (bGtipo_pessoa.isSelected(null)) {
                JOptionPane.showMessageDialog(null, "Favor selecionar o TIPO DE Cliente!");
            } else if (jRBFisico.isSelected()) {
                pfisica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                cliente.setTPCLIENTE("F");
                if (jTFNrCpf.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CPF");
                    jTFNrCpf.grabFocus();
                    return;
                } else {
                    pfisica.setNRCPF(jTFNrCpf.getText());
                }
                if (!jTFrg.getText().equals("")) {
                    pfisica.setNRRG(jTFrg.getText());
                }

                String sexo = jCBSexo.getSelectedItem().toString();
                if (sexo.equals("MASCULINO")) {
                    pfisica.setTPSEXO("M");
                } else {
                    pfisica.setTPSEXO("F");
                }

            } else {
                pjuridica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                cliente.setTPCLIENTE("J");
                if (jTFcnpj.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CNPJ");
                    jTFcnpj.grabFocus();
                    return;
                } else {
                    String cnpj = jTFcnpj.getText();
                    pjuridica.setNRCNPJ(jTFcnpj.getText());

                }
                if (jTFrazaosocial.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe a Razão Social!");
                    jTFrazaosocial.grabFocus();
                    return;
                } else {
                    pjuridica.setRZSOCIAL(jTFrazaosocial.getText());
                }
            }
            endereco.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            String cidadeId = jCBCidade.getSelectedItem().toString();
            try {
                idCidade = cidadeDAO.ConsultaIdcidade(idCidade, cidadeId);
                endereco.setIDCIDADE(idCidade);
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceCidade.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jTFlogradouro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Logradouro");
                jTFlogradouro.grabFocus();
                return;
            } else {
                endereco.setDSLOGRADOURO(jTFlogradouro.getText().toUpperCase());
            }
            if (jTFNumero.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Número do endereço");
                jTFNumero.grabFocus();
                return;
            } else {
                endereco.setDSNUMERO(jTFNumero.getText().toUpperCase());
            }
            if (jTFbairro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Bairro");
                jTFbairro.grabFocus();
                return;
            } else {
                endereco.setDSBAIRRO(jTFbairro.getText().toUpperCase());
            }
            if (jTFcomplemento.getText().equals("")) {
                endereco.setDSCOMPLEMENTO(".");
            } else {
                endereco.setDSCOMPLEMENTO(jTFcomplemento.getText());
            }
            String cep = jTFNrCep.toString();

            if (jTFNrCep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o CEP");
                jTFNrCep.grabFocus();
                return;
            } else {
                endereco.setNRCEP(jTFNrCep.getText());
            }
            endereco.setTPENDERECO("CLIENTE");
            if (jRBFisico.isSelected()) {

                Integer id = pfisica.getIDPESSOA();
                if (id == null) {
                    pfDao.incluir(pfisica);
                }

                endDao.incluir(endereco);
                telefoneDAO.incluir(telefone);
                clienteDAO.incluir(cliente);
            } else {
                Integer id = pjuridica.getIDPESSOA();
                if (id == null) {
                    pjDao.incluir(pjuridica);
                }

                endDao.incluir(endereco);
                telefoneDAO.incluir(telefone);
                clienteDAO.incluir(cliente);
            }

            lcampos.LimparCampos(jTPcliente);
            estadobotoes(false);

        } else {
            if (jTFIdPessoa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Cliente");
                jTFIdPessoa.grabFocus();
                return;
            } else {
                cliente.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
            }

            if (jTFnome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe nome do Cliente");
                jTFnome.grabFocus();
                return;
            } else {
                pessoa.setDSPESSOA(jTFnome.getText());
            }

            cliente.setDTCADASTRO(jTFDtCadastro.getText());
            cliente.setTPSITUACAO(jCBSituacao.getSelectedIndex());

            telefone.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            if (jTFFone1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o número do Telefone");
                jTFFone1.grabFocus();
                return;
            } else {
                telefone.setNRFONE(jTFFone1.getText());

            }
            telefone.setTPFONE("Principal");

            if (bGtipo_pessoa.isSelected(null)) {
                JOptionPane.showMessageDialog(null, "Favor selecionar o TIPO DE Cliente!");
            } else if (jRBFisico.isSelected()) {
                pfisica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                cliente.setTPCLIENTE("F");
                if (jTFNrCpf.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CPF");
                    jTFNrCpf.grabFocus();
                    return;
                } else {
                    pfisica.setNRCPF(jTFNrCpf.getText());
                }
                if (!jTFrg.getText().equals("")) {
                    pfisica.setNRRG(jTFrg.getText());
                }

                String sexo = jCBSexo.getSelectedItem().toString();
                if (sexo.equals("MASCULINO")) {
                    pfisica.setTPSEXO("M");
                } else {
                    pfisica.setTPSEXO("F");
                }

            } else {
                pjuridica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                cliente.setTPCLIENTE("J");
                if (jTFcnpj.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CNPJ");
                    jTFcnpj.grabFocus();
                    return;
                } else {
                    String cnpj = jTFcnpj.getText();
                    pjuridica.setNRCNPJ(jTFcnpj.getText());

                }
                if (jTFrazaosocial.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe a Razão Social!");
                    jTFrazaosocial.grabFocus();
                    return;
                } else {
                    pjuridica.setRZSOCIAL(jTFrazaosocial.getText());
                }
            }
            endereco.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            String cidadeId = jCBCidade.getSelectedItem().toString();
            try {
                idCidade = cidadeDAO.ConsultaIdcidade(idCidade, cidadeId);
                endereco.setIDCIDADE(idCidade);
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceCidade.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jTFlogradouro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Logradouro");
                jTFlogradouro.grabFocus();
                return;
            } else {
                endereco.setDSLOGRADOURO(jTFlogradouro.getText().toUpperCase());
            }
            if (jTFNumero.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Número do endereço");
                jTFNumero.grabFocus();
                return;
            } else {
                endereco.setDSNUMERO(jTFNumero.getText().toUpperCase());
            }
            if (jTFbairro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Bairro");
                jTFbairro.grabFocus();
                return;
            } else {
                endereco.setDSBAIRRO(jTFbairro.getText().toUpperCase());
            }
            if (jTFcomplemento.getText().equals("")) {
                endereco.setDSCOMPLEMENTO(".");
            } else {
                endereco.setDSCOMPLEMENTO(jTFcomplemento.getText());
            }
            String cep = jTFNrCep.toString();

            if (jTFNrCep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o CEP");
                jTFNrCep.grabFocus();
                return;
            } else {
                endereco.setNRCEP(jTFNrCep.getText());
            }
            endereco.setTPENDERECO("CLIENTE");

            if (jRBFisico.isSelected()) {
                pfDao.alterar(pfisica);
                endDao.alterar(endereco);
                telefoneDAO.alterar(telefone);
                clienteDAO.alterar(cliente);
            } else {
                pjDao.alterar(pjuridica);
                endDao.alterar(endereco);
                telefoneDAO.alterar(telefone);
                clienteDAO.alterar(cliente);
            }
            lcampos.LimparCampos(jTPcliente);
            estadobotoes(false);

        }
    }//GEN-LAST:event_jBgravarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        situacao = 1;

        int t = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente EXCLUIR o registro?");
        if (t == 0) {
            endDao.excluir(endereco);
            telefoneDAO.excluir(telefone);
            clienteDAO.excluir(cliente);
        }
        JOptionPane.showMessageDialog(rootPane, "Registro excluido com sucesso!");
        estadobotoes(false);
        lcampos.LimparCampos(jTPcliente);
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncluirActionPerformed
        jTFdtnasc.grabFocus();
        lcampos.LimparCampos(jTPcliente);
        situacao = 1;
        estadobotoes(true);
        cidadeDAO.preenchercidade(jCBCidade, cidade);
        retornadata.RetornaDataAtual(jTFDtCadastro);

    }//GEN-LAST:event_jBIncluirActionPerformed

    private void jRBJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBJuridicaMouseClicked
        jTFNrCpf.setEnabled(false);
        jTFrg.setEnabled(false);
        jCBSexo.setEnabled(false);

        jTFcnpj.setEnabled(true);
        jTFrazaosocial.setEnabled(true);

        String ID = jTFIdPessoa.getText();

        pjuridica.setIDPESSOA(Integer.parseInt(ID));
        pjDao.retornadados(pjuridica);
        jTFcnpj.setText(pjuridica.getNRCNPJ());
        jTFrazaosocial.setText(pjuridica.getRZSOCIAL());
    }//GEN-LAST:event_jRBJuridicaMouseClicked

    private void jRBFisicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBFisicoMouseClicked

        jTFNrCpf.setEnabled(true);
        jTFrg.setEnabled(true);
        jCBSexo.setEnabled(true);

        jTFcnpj.setEnabled(false);
        jTFrazaosocial.setEnabled(false);

        String ID = jTFIdPessoa.getText();

        pfisica.setIDPESSOA(Integer.parseInt(ID));
        pfDao.retornadados(pfisica);
        jTFNrCpf.setText(pfisica.getNRCPF());
        jTFrg.setText(pfisica.getNRRG());
        String sexo = pfisica.getTPSEXO();

        if (sexo.equals("M")) {
            jCBSexo.setSelectedItem("MASCULINO");
        } else {
            jCBSexo.setSelectedItem("FEMININO");
        }

    }//GEN-LAST:event_jRBFisicoMouseClicked

    private void jCbPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbPesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbPesquisa1ActionPerformed

    private void jBtPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisa1ActionPerformed

        PreencherJtableGenerico preencher = new PreencherJtableGenerico();
        switch (jCbPesquisa1.getSelectedIndex()) {
            case 0: {
                clienteDAO.consulta(cliente);
                preencher.PreencherJComboBox(jTbPesquisa1, cliente.getRetorno());
                return;
            }
            case 1: {
                pessoa.setDSPESSOA(jTFPesquisa1.getText().toUpperCase());
                clienteDAO.consultadescricao(pessoa, cliente);
                preencher.PreencherJComboBox(jTbPesquisa1, cliente.getRetorno());
                return;
            }
        }
    }//GEN-LAST:event_jBtPesquisa1ActionPerformed

    private void jTbPesquisa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbPesquisa1MouseClicked
        if (evt.getClickCount() == 1) {
            int linha = jTbPesquisa1.getSelectedRow();
            String ID = (String) jTbPesquisa1.getValueAt(linha, 0);
            Integer idpessoa = 0;

            cliente.setIDPESSOA(Integer.parseInt(ID));
            clienteDAO.retornadados(cliente);

            telefone.setIDPESSOA(Integer.parseInt(ID));
            telefoneDAO.retornadados(telefone);

            pessoa.setIDPESSOA(Integer.parseInt(ID));
            pessoaDao.retornadados(pessoa);

            pfisica.setIDPESSOA(Integer.parseInt(ID));
            pfDao.retornadados(pfisica);

            pjuridica.setIDPESSOA(Integer.parseInt(ID));
            pjDao.retornadados(pjuridica);

            endereco.setIDPESSOA(Integer.parseInt(ID));
            endDao.retornadados(endereco);

            String tpPessoa = cliente.getTPCLIENTE();
            Integer tpSituacao = cliente.getTPSITUACAO();

            jTFIdPessoa.setText(Integer.toString(cliente.getIDPESSOA()));
            jTFnome.setText(pessoa.getDSPESSOA());

            jCBSituacao.setSelectedIndex(tpSituacao);

            if (tpPessoa.equals("F")) {
                jRBFisico.setSelected(true);

                jTFcnpj.setEnabled(false);
                jTFrazaosocial.setEnabled(false);

                jTFNrCpf.setText(pfisica.getNRCPF());
                jTFrg.setText(pfisica.getNRRG());
                String sexo = pfisica.getTPSEXO();
                if (sexo.equals("M")) {
                    jCBSexo.setSelectedIndex(1);
                } else {
                    jCBSexo.setSelectedIndex(0);
                }

            } else {
                jRBJuridica.setSelected(false);

                jTFNrCpf.setEnabled(false);
                jTFrg.setEnabled(false);
                jCBSexo.setEnabled(false);

                jTFrazaosocial.setText(pjuridica.getRZSOCIAL());
                jTFcnpj.setText(pjuridica.getNRCNPJ());
            }
            jTFdtnasc.setText(pessoa.getDTNASC());
            jTFDtCadastro.setText(cliente.getDTCADASTRO());
            jTFFone1.setText(telefone.getNRFONE());

            jTFlogradouro.setText(endereco.getDSLOGRADOURO());
            jTFNumero.setText(endereco.getDSNUMERO());
            jTFcomplemento.setText(endereco.getDSCOMPLEMENTO());
            jTFbairro.setText(endereco.getDSBAIRRO());
            jTFNrCep.setText(endereco.getNRCEP());

            cidadeDAO.preenchercidade(jCBCidade, cidade);

            Integer idcidade = endereco.getIDCIDADE();
            cidade.setIDCIDADE(idcidade);
            cidadeDAO.retornacidade(cidade);
            jCBCidade.setSelectedItem(cidade.getDscidade());

        }

        estadobotoes(false);
        jTPcliente.setSelectedIndex(0);
    }//GEN-LAST:event_jTbPesquisa1MouseClicked

    private void jTFNrCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNrCpfFocusLost

        String cpff = jTFNrCpf.getText().toString();
        String strSemPontos = jTFNrCpf.getText().replace(".", "");
        char[] cpf = jTFNrCpf.getText().replace(".", "").replace("-", "").toCharArray();
        int qtdCpf = cpf.length;
        if (jTFNrCpf.equals("00000000000") || jTFNrCpf.equals("11111111111")
                || jTFNrCpf.equals("22222222222") || jTFNrCpf.equals("33333333333")
                || jTFNrCpf.equals("44444444444") || jTFNrCpf.equals("55555555555")
                || jTFNrCpf.equals("66666666666") || jTFNrCpf.equals("77777777777")
                || jTFNrCpf.equals("88888888888") || jTFNrCpf.equals("99999999999")
                || (qtdCpf != 11)) {
            jTFNrCpf.setText("");
            jTFNrCpf.grabFocus();
            JOptionPane.showMessageDialog(null, "Digite um CPF Válido!");
        } else {

            for (int i = 0; i < qtdCpf; i++) {
                char digCpf;
                digCpf = cpf[i];
                String charCPF;
                if (i == 0) {
                    charCPF = String.valueOf(digCpf);
                    dig1 = (10 * Integer.parseInt(charCPF));
                    dig21 = (11 * Integer.parseInt(charCPF));
                } else if (i == 1) {
                    charCPF = String.valueOf(digCpf);
                    dig2 = (9 * Integer.parseInt(charCPF));
                    dig22 = (10 * Integer.parseInt(charCPF));
                } else if (i == 2) {
                    charCPF = String.valueOf(digCpf);
                    dig3 = (8 * Integer.parseInt(charCPF));
                    dig23 = (9 * Integer.parseInt(charCPF));
                } else if (i == 3) {
                    charCPF = String.valueOf(digCpf);
                    dig4 = (7 * Integer.parseInt(charCPF));
                    dig24 = (8 * Integer.parseInt(charCPF));
                } else if (i == 4) {
                    charCPF = String.valueOf(digCpf);
                    dig5 = (6 * Integer.parseInt(charCPF));
                    dig25 = (7 * Integer.parseInt(charCPF));
                } else if (i == 5) {
                    charCPF = String.valueOf(digCpf);
                    dig6 = (5 * Integer.parseInt(charCPF));
                    dig26 = (6 * Integer.parseInt(charCPF));
                } else if (i == 6) {
                    charCPF = String.valueOf(digCpf);
                    dig7 = (4 * Integer.parseInt(charCPF));
                    dig27 = (5 * Integer.parseInt(charCPF));
                } else if (i == 7) {
                    charCPF = String.valueOf(digCpf);
                    dig8 = (3 * Integer.parseInt(charCPF));
                    dig28 = (4 * Integer.parseInt(charCPF));
                } else if (i == 8) {
                    charCPF = String.valueOf(digCpf);
                    dig9 = (2 * Integer.parseInt(charCPF));
                    dig29 = (3 * Integer.parseInt(charCPF));
                } else if (i == 9) {
                    charCPF = String.valueOf(digCpf);
                    dig10 = Integer.parseInt(charCPF);
                    dig210 = (2 * Integer.parseInt(charCPF));
                } else if (i == 10) {
                    charCPF = String.valueOf(digCpf);
                    dig11 = Integer.parseInt(charCPF);
                    dig211 = Integer.parseInt(charCPF);
                }
            }
            Integer somaDig10 = (dig1 + dig2 + dig3 + dig4 + dig5 + dig6 + dig7 + dig8 + dig9);
            Integer restoDivDig10 = (somaDig10 % 11);
            Integer digVerif1 = (11 - restoDivDig10);
            if (digVerif1 > 9) {
                digVerif1 = 0;
            }
            Integer digVerif2 = 0;
            if (dig10 == digVerif1) {
                Integer somaDig11 = (dig21 + dig22 + dig23 + dig24 + dig25 + dig26 + dig27 + dig28 + dig29 + dig210);
                Integer restoDivDig11 = (somaDig11 % 11);
                digVerif2 = (11 - restoDivDig11);
                if (digVerif2 > 9) {
                    digVerif2 = 0;
                }
                if (dig11 != digVerif2) {
                    jTFNrCpf.setText("");
                    jTFNrCpf.grabFocus();
                    JOptionPane.showMessageDialog(null, "Insira um CPF valido!");
                }
            } else {
                jTFNrCpf.setText("");
                jTFNrCpf.grabFocus();
                JOptionPane.showMessageDialog(null, "Insira um CPF valido!");
            }
        }
    }//GEN-LAST:event_jTFNrCpfFocusLost

    private void jRBFisicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRBFisicoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBFisicoKeyTyped

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed

        int t = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente cancelar o cadastro?");
        if (t == 0) {
            situacao = 2;
            lcampos.LimparCampos(jPCadastro);
            estadobotoes(false);
        }
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTFcnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFcnpjFocusLost
        char[] cnpj = jTFcnpj.getText().toCharArray();
        int qtdCnpj = cnpj.length;

        if (jTFcnpj.equals("00000000000000") || jTFcnpj.equals("11111111111111")
                || jTFcnpj.equals("22222222222222") || jTFcnpj.equals("33333333333333")
                || jTFcnpj.equals("44444444444444") || jTFcnpj.equals("55555555555555")
                || jTFcnpj.equals("66666666666666") || jTFcnpj.equals("77777777777777")
                || jTFcnpj.equals("88888888888888") || jTFcnpj.equals("99999999999999")
                || (qtdCnpj != 18)) {
            jTFcnpj.setText("");
            jTFcnpj.grabFocus();
            JOptionPane.showMessageDialog(null, "Digite um CNPJ Válido!");
        } else {

            char dig13, dig14;
            int sm, result, dig, peso;

            sm = 0;
            peso = 2;
            for (int i = 14; i >= 0; i--) {

                dig = (int) (jTFcnpj.getText().charAt(i) - 48);
                if (dig != -1) {
                    if (dig != -2) {
                        if (dig != -3) {

                            sm = sm + (dig * peso);
                            peso = peso + 1;
                            if (peso == 10) {
                                peso = 2;
                            }
                        }
                    }
                }
            }

            result = sm % 11;
            if ((result == 0) || (result == 1)) {
                dig13 = '0';
            } else {
                dig13 = (char) ((11 - result) + 48);
            }

            // Calculo do 2o. Digito Verificador
            sm = 0;
            peso = 2;
            for (int i = 16; i >= 0; i--) {
                dig = (int) (jTFcnpj.getText().charAt(i) - 48);
                if (dig != -1) {
                    if (dig != -2) {
                        if (dig != -3) {
                            sm = sm + (dig * peso);
                            peso = peso + 1;
                            if (peso == 10) {
                                peso = 2;
                            }
                        }
                    }
                }
            }

            result = sm % 11;
            if ((result == 0) || (result == 1)) {
                dig14 = '0';
            } else {
                dig14 = (char) ((11 - result) + 48);
            }

            // Verifica se os dígitos calculados conferem com os dígitos informados.
            if ((dig13 != jTFcnpj.getText().charAt(16)) || (dig14 != jTFcnpj.getText().charAt(17))) {
                jTFcnpj.setText("");
                jTFcnpj.grabFocus();
                JOptionPane.showMessageDialog(null, "Digite um CNPJ Válido!");
            }
        }
    }//GEN-LAST:event_jTFcnpjFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfaceCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BaddPessoas;
    private javax.swing.JLabel Sexo;
    private javax.swing.ButtonGroup bGtipo_pessoa;
    private javax.swing.JButton jBAlterar1;
    private javax.swing.JButton jBIncluir;
    private javax.swing.JButton jBPesquisar2;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBgravar;
    private javax.swing.JButton jBtPesquisa1;
    private javax.swing.JComboBox jCBCidade;
    private javax.swing.JComboBox jCBSexo;
    private javax.swing.JComboBox<String> jCBSituacao;
    private javax.swing.JComboBox jCbPesquisa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPConsulta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelbotoes;
    private javax.swing.JPanel jPpfisica;
    private javax.swing.JPanel jPpjuridica;
    private javax.swing.JRadioButton jRBFisico;
    private javax.swing.JRadioButton jRBJuridica;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFDtCadastro;
    private javax.swing.JFormattedTextField jTFFone1;
    private javax.swing.JTextField jTFIdPessoa;
    private javax.swing.JFormattedTextField jTFNrCep;
    private javax.swing.JFormattedTextField jTFNrCpf;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFPesquisa1;
    private javax.swing.JTextField jTFbairro;
    private javax.swing.JFormattedTextField jTFcnpj;
    private javax.swing.JTextField jTFcomplemento;
    private javax.swing.JTextField jTFdtnasc;
    private javax.swing.JTextField jTFlogradouro;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFrazaosocial;
    private javax.swing.JFormattedTextField jTFrg;
    private javax.swing.JTabbedPane jTPcliente;
    private javax.swing.JTable jTbPesquisa1;
    // End of variables declaration//GEN-END:variables

    private void estadobotoes(boolean situacao) {
        jBIncluir.setEnabled(!situacao);
        jBAlterar1.setEnabled(!situacao);
        jBexcluir.setEnabled(!situacao);
        jBgravar.setEnabled(situacao);
        jBcancelar.setEnabled(situacao);
    }
}
