package br.tcc.Interface;

import br.tcc.ConsultaSimples.ConsultaProduto;
import br.tcc.Validacoes.LimparCampos;
import br.tcc.Validacoes.PreencherJtableGenerico;
import br.tcc.Validacoes.RetornaDataAtual;
import br.tcc.Validacoes.ValidaNumero;
import br.tcc.classe.Cidade;
import br.tcc.classe.Endereco;
import br.tcc.classe.Fornecedor;
import br.tcc.classe.Pessoa;
import br.tcc.classe.PessoaFisica;
import br.tcc.classe.PessoaJuridica;
import br.tcc.classe.ProdutosFornecedor;
import br.tcc.classe.Telefone;
import br.tcc.dao.CidadeDAO;
import br.tcc.dao.EnderecoDAO;
import br.tcc.dao.FornecedorDAO;
import br.tcc.dao.PessoaDAO;
import br.tcc.dao.PessoaFisicaDAO;
import br.tcc.dao.PessoaJuridicaDAO;
import br.tcc.dao.ProdutosFornecedorDAO;
import br.tcc.dao.TelefoneDAO;
import br.tcc.dao.UsuarioDAO;
import java.awt.List;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joao Paulo
 */
public class InterfaceFornecedor extends javax.swing.JFrame {

    Integer dig1, dig2, dig3, dig4, dig5, dig6, dig7, dig8, dig9, dig10, dig11;
    Integer dig21, dig22, dig23, dig24, dig25, dig26, dig27, dig28, dig29, dig210, dig211;
    LimparCampos lcampos = new LimparCampos();
    private int situacao = 0;
    CidadeDAO cidadeDAO = new CidadeDAO();
    RetornaDataAtual retornadata = new RetornaDataAtual();
    Cidade cidade = new Cidade();
    Fornecedor fornecedor = new Fornecedor();
    PessoaFisica pfisica = new PessoaFisica();
    PessoaJuridica pjuridica = new PessoaJuridica();
    Endereco endereco = new Endereco();
    PessoaFisicaDAO pfdao = new PessoaFisicaDAO();
    PessoaJuridicaDAO pjdao = new PessoaJuridicaDAO();
    EnderecoDAO endDAO = new EnderecoDAO();
    FornecedorDAO fornDAO = new FornecedorDAO();
    Telefone telefone = new Telefone();
    TelefoneDAO telefoneDAO = new TelefoneDAO();
    Pessoa pessoa = new Pessoa();
    PessoaDAO pessoaDAO = new PessoaDAO();
    ProdutosFornecedor prodFornece = new ProdutosFornecedor();
    ProdutosFornecedorDAO prodfornecedao = new ProdutosFornecedorDAO();

    /**
     * Creates new form InterfacePessoa
     */
    public InterfaceFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGtipo_pessoa = new javax.swing.ButtonGroup();
        jTPFornecedor = new javax.swing.JTabbedPane();
        jPcadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFIdPessoa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFnome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRBFisico = new javax.swing.JRadioButton();
        jRBJuridica = new javax.swing.JRadioButton();
        jPpfisica = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTFrg = new javax.swing.JTextField();
        jTFNrCpf = new javax.swing.JTextField();
        Sexo = new javax.swing.JLabel();
        jCBSexo = new javax.swing.JComboBox();
        jPpjuridica = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFrazaosocial = new javax.swing.JTextField();
        jTFNrCnpj = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTFproduto = new javax.swing.JTextField();
        jBpesquisar = new javax.swing.JButton();
        jTFdsproduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTitens = new javax.swing.JTable();
        jBAddProduto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBincluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBgravar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jTFCodigoItem = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jBPesquisar = new javax.swing.JButton();
        jTFDsItem = new javax.swing.JTextField();
        jBAdicionar = new javax.swing.JButton();
        jTFDtCadastro = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCBCidade = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTFlogradouro = new javax.swing.JTextField();
        jTFNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFbairro = new javax.swing.JTextField();
        jTFcomplemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFNrCep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFDtNasc = new javax.swing.JFormattedTextField();
        jBPesquisarPessoa = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jCBTpSituação = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jTFVlLimite = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTFFone1 = new javax.swing.JTextField();
        jPconsulta = new javax.swing.JPanel();
        jCbPesquisa2 = new javax.swing.JComboBox();
        jTFPesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbPesquisa = new javax.swing.JTable();
        jBtPesquisa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Fornecedor");

        jLabel1.setText("Código");

        jLabel8.setText("Email");

        jLabel9.setText("Nome");

        jLabel10.setText("Data de cadastro");

        bGtipo_pessoa.add(jRBFisico);
        jRBFisico.setText("Física");
        jRBFisico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBFisicoMouseClicked(evt);
            }
        });

        bGtipo_pessoa.add(jRBJuridica);
        jRBJuridica.setText("Juridica");
        jRBJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBJuridicaMouseClicked(evt);
            }
        });

        jPpfisica.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Física"));

        jLabel11.setText("CPF");

        jLabel12.setText("RG");

        jTFNrCpf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFNrCpfMouseClicked(evt);
            }
        });
        jTFNrCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNrCpfFocusLost(evt);
            }
        });

        Sexo.setText("Sexo");

        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FEMININO", "MASCULINO" }));

        javax.swing.GroupLayout jPpfisicaLayout = new javax.swing.GroupLayout(jPpfisica);
        jPpfisica.setLayout(jPpfisicaLayout);
        jPpfisicaLayout.setHorizontalGroup(
            jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpfisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPpfisicaLayout.createSequentialGroup()
                        .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTFNrCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jTFrg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Sexo)
                    .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPpfisicaLayout.setVerticalGroup(
            jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpfisicaLayout.createSequentialGroup()
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNrCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sexo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPpjuridica.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Juridica"));

        jLabel14.setText("CNPJ");

        jLabel16.setText("Razão Social");

        jTFNrCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFNrCnpjFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPpjuridicaLayout = new javax.swing.GroupLayout(jPpjuridica);
        jPpjuridica.setLayout(jPpjuridicaLayout);
        jPpjuridicaLayout.setHorizontalGroup(
            jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpjuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNrCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jTFrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPpjuridicaLayout.setVerticalGroup(
            jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpjuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNrCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do fornecedor"));

        jLabel18.setText("Produto");

        jBpesquisar.setText("Pesquisar");

        jTitens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTitens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTitensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTitens);

        jBAddProduto.setText("Adicionar");

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jBincluir.setText("Incluir");
        jBincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincluirActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBgravar.setText("Gravar");
        jBgravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgravarActionPerformed(evt);
            }
        });

        jBcancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jBincluir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jBgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jBgravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBincluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTFCodigoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoItemActionPerformed(evt);
            }
        });

        jLabel19.setText("Código");

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarMouseClicked(evt);
            }
        });
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBpesquisar)
                .addGap(568, 568, 568)
                .addComponent(jTFdsproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAddProduto)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTFCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFDsItem, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBAdicionar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(441, 441, 441))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar)
                    .addComponent(jTFDsItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTFproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBpesquisar)
                    .addComponent(jTFdsproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAddProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setText("Tipo de Pessoa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel2.setText("Cidade");

        jLabel3.setText("Logradouro");

        jLabel4.setText("Número");

        jLabel6.setText("Complemento");

        jLabel5.setText("Bairro");

        jLabel7.setText("CEP");

        jTFNrCep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFNrCepMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTFbairro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTFlogradouro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jTFcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jTFNrCep))))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFlogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNrCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel13.setText("Data de Nascimento");

        try {
            jTFDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jBPesquisarPessoa.setText("Pesquisar");
        jBPesquisarPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarPessoaMouseClicked(evt);
            }
        });

        jLabel17.setText("Situação");

        jCBTpSituação.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "LICENÇA", "FÉRIAS", "INATIVO" }));

        jLabel15.setText("Limite para Compra");

        jLabel24.setText("Telefone");

        javax.swing.GroupLayout jPcadastroLayout = new javax.swing.GroupLayout(jPcadastro);
        jPcadastro.setLayout(jPcadastroLayout);
        jPcadastroLayout.setHorizontalGroup(
            jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroLayout.createSequentialGroup()
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPcadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFDtCadastro)
                                    .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPcadastroLayout.createSequentialGroup()
                                        .addComponent(jRBFisico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRBJuridica))
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jTFDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBTpSituação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addGap(30, 30, 30)
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFVlLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(198, 198, 198))
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPcadastroLayout.createSequentialGroup()
                                        .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBPesquisarPessoa))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPcadastroLayout.createSequentialGroup()
                                        .addComponent(jTFemail)
                                        .addGap(15, 15, 15))))))
                    .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPcadastroLayout.createSequentialGroup()
                            .addComponent(jPpfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(jPpjuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFFone1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPcadastroLayout.setVerticalGroup(
            jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroLayout.createSequentialGroup()
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarPessoa)
                    .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcadastroLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel20))
                        .addGap(1, 1, 1)
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRBFisico)
                                .addComponent(jRBJuridica))
                            .addComponent(jTFDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPcadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFVlLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPcadastroLayout.createSequentialGroup()
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel17))
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBTpSituação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcadastroLayout.createSequentialGroup()
                        .addComponent(jPpfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPpjuridica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, Short.MAX_VALUE)
                .addGap(423, 423, 423))
        );

        jTPFornecedor.addTab("Cadastro", jPcadastro);

        jCbPesquisa2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "funcionário " }));

        jTbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fornecedor", "Data Cadastro", "Valor Limite", "Telefone Comercial"
            }
        ));
        jTbPesquisa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTbPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbPesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTbPesquisa);

        jBtPesquisa1.setText("Pesquisar");
        jBtPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPconsultaLayout = new javax.swing.GroupLayout(jPconsulta);
        jPconsulta.setLayout(jPconsultaLayout);
        jPconsultaLayout.setHorizontalGroup(
            jPconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPconsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPconsultaLayout.createSequentialGroup()
                        .addComponent(jCbPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisa1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPconsultaLayout.setVerticalGroup(
            jPconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPconsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisa1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPFornecedor.addTab("Consulta", jPconsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(791, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNrCpfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNrCpfMouseClicked

        ValidaNumero validaNumero = new ValidaNumero();
        validaNumero.ValidaNumero(jTFNrCpf);
    }//GEN-LAST:event_jTFNrCpfMouseClicked

    private void jTFNrCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNrCpfFocusLost
        char[] cpf = jTFNrCpf.getText().toCharArray();
        int qtdCpf = cpf.length;
        if (jTFNrCpf.equals("00000000000000") || jTFNrCpf.equals("11111111111111")
                || jTFNrCpf.equals("22222222222222") || jTFNrCpf.equals("33333333333333")
                || jTFNrCpf.equals("44444444444444") || jTFNrCpf.equals("55555555555555")
                || jTFNrCpf.equals("66666666666666") || jTFNrCpf.equals("77777777777777")
                || jTFNrCpf.equals("88888888888888") || jTFNrCpf.equals("99999999999999")
                || (qtdCpf != 11)) {
            jTFNrCpf.setText("");
            jTFNrCpf.grabFocus();
            JOptionPane.showMessageDialog(null, "Digite um CPF Válido!");
        } else {

            for (int i = 0; i < qtdCpf; i++) {
                char digCpf;
                digCpf = cpf[i];
                String charCPF;
                if (i == 0) {
                    charCPF = String.valueOf(digCpf);
                    dig1 = (10 * Integer.parseInt(charCPF));
                    dig21 = (11 * Integer.parseInt(charCPF));
                } else if (i == 1) {
                    charCPF = String.valueOf(digCpf);
                    dig2 = (9 * Integer.parseInt(charCPF));
                    dig22 = (10 * Integer.parseInt(charCPF));
                } else if (i == 2) {
                    charCPF = String.valueOf(digCpf);
                    dig3 = (8 * Integer.parseInt(charCPF));
                    dig23 = (9 * Integer.parseInt(charCPF));
                } else if (i == 3) {
                    charCPF = String.valueOf(digCpf);
                    dig4 = (7 * Integer.parseInt(charCPF));
                    dig24 = (8 * Integer.parseInt(charCPF));
                } else if (i == 4) {
                    charCPF = String.valueOf(digCpf);
                    dig5 = (6 * Integer.parseInt(charCPF));
                    dig25 = (7 * Integer.parseInt(charCPF));
                } else if (i == 5) {
                    charCPF = String.valueOf(digCpf);
                    dig6 = (5 * Integer.parseInt(charCPF));
                    dig26 = (6 * Integer.parseInt(charCPF));
                } else if (i == 6) {
                    charCPF = String.valueOf(digCpf);
                    dig7 = (4 * Integer.parseInt(charCPF));
                    dig27 = (5 * Integer.parseInt(charCPF));
                } else if (i == 7) {
                    charCPF = String.valueOf(digCpf);
                    dig8 = (3 * Integer.parseInt(charCPF));
                    dig28 = (4 * Integer.parseInt(charCPF));
                } else if (i == 8) {
                    charCPF = String.valueOf(digCpf);
                    dig9 = (2 * Integer.parseInt(charCPF));
                    dig29 = (3 * Integer.parseInt(charCPF));
                } else if (i == 9) {
                    charCPF = String.valueOf(digCpf);
                    dig10 = Integer.parseInt(charCPF);
                    dig210 = (2 * Integer.parseInt(charCPF));
                } else if (i == 10) {
                    charCPF = String.valueOf(digCpf);
                    dig11 = Integer.parseInt(charCPF);
                    dig211 = Integer.parseInt(charCPF);
                }
            }
            Integer somaDig10 = (dig1 + dig2 + dig3 + dig4 + dig5 + dig6 + dig7 + dig8 + dig9);
            Integer restoDivDig10 = (somaDig10 % 11);
            Integer digVerif1 = (11 - restoDivDig10);
            if (digVerif1 > 9) {
                digVerif1 = 0;
            }
            Integer digVerif2 = 0;
            if (dig10 == digVerif1) {
                Integer somaDig11 = (dig21 + dig22 + dig23 + dig24 + dig25 + dig26 + dig27 + dig28 + dig29 + dig210);
                Integer restoDivDig11 = (somaDig11 % 11);
                digVerif2 = (11 - restoDivDig11);
                if (digVerif2 > 9) {
                    digVerif2 = 0;
                }
                if (dig11 != digVerif2) {
                    jTFNrCpf.setText("");
                    jTFNrCpf.grabFocus();
                    JOptionPane.showMessageDialog(null, "Insira um CPF valido!");
                }
            } else {
                jTFNrCpf.setText("");
                jTFNrCpf.grabFocus();
                JOptionPane.showMessageDialog(null, "Insira um CPF valido!");
            }
        }
    }//GEN-LAST:event_jTFNrCpfFocusLost

    private void jTFNrCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNrCnpjFocusLost

        char[] cnpj = jTFNrCnpj.getText().toCharArray();
        int qtdCnpj = cnpj.length;

        if (jTFNrCnpj.equals("00000000000000") || jTFNrCnpj.equals("11111111111111")
                || jTFNrCnpj.equals("22222222222222") || jTFNrCnpj.equals("33333333333333")
                || jTFNrCnpj.equals("44444444444444") || jTFNrCnpj.equals("55555555555555")
                || jTFNrCnpj.equals("66666666666666") || jTFNrCnpj.equals("77777777777777")
                || jTFNrCnpj.equals("88888888888888") || jTFNrCnpj.equals("99999999999999")
                || (qtdCnpj != 14)) {
            jTFNrCnpj.setText("");
            jTFNrCnpj.grabFocus();
            JOptionPane.showMessageDialog(null, "Digite um CNPJ Válido!");
        } else {

            char dig13, dig14;
            int sm, result, dig, peso;

            sm = 0;
            peso = 2;
            for (int i = 11; i >= 0; i--) {

                dig = (int) (jTFNrCnpj.getText().charAt(i) - 48);
                sm = sm + (dig * peso);
                peso = peso + 1;
                if (peso == 10) {
                    peso = 2;
                }
            }

            result = sm % 11;
            if ((result == 0) || (result == 1)) {
                dig13 = '0';
            } else {
                dig13 = (char) ((11 - result) + 48);
            }

            // Calculo do 2o. Digito Verificador
            sm = 0;
            peso = 2;
            for (int i = 12; i >= 0; i--) {
                dig = (int) (jTFNrCnpj.getText().charAt(i) - 48);
                sm = sm + (dig * peso);
                peso = peso + 1;
                if (peso == 10) {
                    peso = 2;
                }
            }

            result = sm % 11;
            if ((result == 0) || (result == 1)) {
                dig14 = '0';
            } else {
                dig14 = (char) ((11 - result) + 48);
            }

            // Verifica se os dígitos calculados conferem com os dígitos informados.
            if ((dig13 != jTFNrCnpj.getText().charAt(12)) || (dig14 != jTFNrCnpj.getText().charAt(13))) {
                jTFNrCnpj.setText("");
                jTFNrCnpj.grabFocus();
                JOptionPane.showMessageDialog(null, "Digite um CNPJ Válido!");
            }
        }
    }//GEN-LAST:event_jTFNrCnpjFocusLost

    private void jTFCodigoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoItemActionPerformed

    private void jBincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincluirActionPerformed

        jTFlogradouro.grabFocus();
        lcampos.LimparCampos(jTPFornecedor);
        situacao = 1;
        estadobotoes(true);
        cidadeDAO.preenchercidade(jCBCidade, cidade);
        retornadata.RetornaDataAtual(jTFDtCadastro);
    }//GEN-LAST:event_jBincluirActionPerformed

    private void jBPesquisarPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarPessoaMouseClicked

        final InterfaceRetornaPessoa retornaPessoa = new InterfaceRetornaPessoa();
        retornaPessoa.setVisible(true);
        retornaPessoa.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdPessoa.setText(retornaPessoa.retornaId);
                jTFnome.setText(retornaPessoa.retornaDsPessoa);
                jTFDtNasc.setText(retornaPessoa.retornaDtNasc);
            }
        });
    }//GEN-LAST:event_jBPesquisarPessoaMouseClicked

    private void jRBFisicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBFisicoMouseClicked
        jTFNrCpf.setEnabled(true);
        jTFrg.setEnabled(true);
        jCBSexo.setEnabled(true);

        jTFNrCnpj.setEnabled(false);
        jTFrazaosocial.setEnabled(false);

        String ID = jTFIdPessoa.getText();

        pfisica.setIDPESSOA(Integer.parseInt(ID));
        pfdao.retornadados(pfisica);
        jTFNrCpf.setText(pfisica.getNRCPF());
        jTFrg.setText(pfisica.getNRRG());
        String sexo = pfisica.getTPSEXO();

        if (sexo.equals("M")) {
            jCBSexo.setSelectedItem("MASCULINO");
        } else {
            jCBSexo.setSelectedItem("FEMININO");
        }
    }//GEN-LAST:event_jRBFisicoMouseClicked

    private void jRBJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBJuridicaMouseClicked
        jTFNrCpf.setEnabled(false);
        jTFrg.setEnabled(false);
        jCBSexo.setEnabled(false);

        jTFNrCnpj.setEnabled(true);
        jTFrazaosocial.setEnabled(true);
    }//GEN-LAST:event_jRBJuridicaMouseClicked

    private void jBPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarMouseClicked

        final ConsultaProduto consProd = new ConsultaProduto();

        consProd.setVisible(true);
        consProd.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                jTFCodigoItem.setText(consProd.retornaId);
                jTFDsItem.setText(consProd.retornaDsProduto);
            }
        });

    }//GEN-LAST:event_jBPesquisarMouseClicked

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed

        if (!jTFCodigoItem.getText().equals("")) {
            if (!jTFDsItem.getText().equals("")) {
                IncluirLista();
                jTFCodigoItem.setText("");
                jTFDsItem.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Informe o codigo do produto !");
                jTFCodigoItem.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Informe o nome do produto!");
            jTFDsItem.grabFocus();
        }
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        situacao = 2;
        estadobotoes(true);
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
       situacao = 1;
        
        int t = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente EXCLUIR o registro?");
        if (t == 0) {
            if (jRBFisico.isSelected()) {
                pfdao.excluir(pfisica);
                endDAO.excluir(endereco);
                telefoneDAO.excluir(telefone);
                prodfornecedao.excluir(prodFornece);
                fornDAO.excluir(fornecedor);
            } else {
                pjdao.excluir(pjuridica);
                endDAO.excluir(endereco);
                prodfornecedao.excluir(prodFornece);
                telefoneDAO.excluir(telefone);
                fornDAO.excluir(fornecedor);
            }
            JOptionPane.showMessageDialog(rootPane, "Registro excluido com sucesso!");
            estadobotoes(false);
        }
        lcampos.LimparCampos(jPcadastro);

    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBgravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgravarActionPerformed

        Integer idCidade = null;
        if (situacao == 1) {
            if (jTFIdPessoa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Fornecedor");
                jTFIdPessoa.grabFocus();
                return;
            } else {
                fornecedor.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
            }

            fornecedor.setDTCADASTRO(jTFDtCadastro.getText());
            fornecedor.setTPSITUACAO(jCBTpSituação.getSelectedIndex());

            if (jTFVlLimite.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Valor Máximo de Compra");
                jTFVlLimite.grabFocus();
                return;
            } else {
                fornecedor.setVLLIMITE(Double.parseDouble(jTFVlLimite.getText()));
            }

            if (jTFemail.getText().equals("")) {
                fornecedor.setDSEMAIL("-");
                return;
            } else {
                fornecedor.setDSEMAIL(jTFemail.getText());
            }

            if (bGtipo_pessoa.isSelected(null)) {
                JOptionPane.showMessageDialog(null, "Favor selecionar o TIPO DE PESSOA!");
            } else if (jRBFisico.isSelected()) {

                pfisica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                fornecedor.setTPPESSOA("F");
                if (jTFNrCpf.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CPF");
                    jTFNrCpf.grabFocus();
                    return;
                } else {
                    pfisica.setNRCPF(jTFNrCpf.getText());
                }
                if (!jTFrg.getText().equals("")) {
                    pfisica.setNRRG(jTFrg.getText());
                }
                String sexo = jCBSexo.getSelectedItem().toString();
                if (sexo.equals("MASCULINO")) {
                    pfisica.setTPSEXO("M");
                } else {
                    pfisica.setTPSEXO("F");
                }

            } else {
                pjuridica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                fornecedor.setTPPESSOA("J");
                if (jTFNrCnpj.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CNPJ");
                    jTFNrCnpj.grabFocus();
                    return;
                } else {
                    String cnpj = jTFNrCnpj.getText();
                    pjuridica.setNRCNPJ(jTFNrCnpj.getText());

                }
                if (jTFrazaosocial.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe a Razão Social!");
                    jTFrazaosocial.grabFocus();
                    return;
                } else {
                    pjuridica.setRZSOCIAL(jTFrazaosocial.getText());
                }
            }
            if (jTFFone1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o número do Telefone");
                jTFFone1.grabFocus();
                return;
            } else {
                telefone.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                telefone.setNRFONE(jTFFone1.getText());
                telefone.setTPFONE("Comercial");
            }
            endereco.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            String cidadeId = jCBCidade.getSelectedItem().toString();
            try {
                idCidade = cidadeDAO.ConsultaIdcidade(idCidade, cidadeId);
                endereco.setIDCIDADE(idCidade);
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceCidade.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jTFlogradouro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Logradouro");
                jTFlogradouro.grabFocus();
                return;
            } else {
                endereco.setDSLOGRADOURO(jTFlogradouro.getText().toUpperCase());
            }
            if (jTFNumero.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Número do endereço");
                jTFNumero.grabFocus();
                return;
            } else {
                endereco.setDSNUMERO(jTFNumero.getText().toUpperCase());
            }
            if (jTFbairro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Bairro");
                jTFbairro.grabFocus();
                return;
            } else {
                endereco.setDSBAIRRO(jTFbairro.getText().toUpperCase());
            }
            if (jTFcomplemento.getText().equals("")) {
                endereco.setDSCOMPLEMENTO(".");
            } else {
                endereco.setDSCOMPLEMENTO(jTFcomplemento.getText());
            }
            String cep = jTFNrCep.toString();

            if (jTFNrCep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o CEP");
                jTFNrCep.grabFocus();
                return;
            } else {
                endereco.setNRCEP(jTFNrCep.getText());
            }
            endereco.setTPENDERECO("COMERCIAL");

            prodFornece.setIDFORNECEDOR(Integer.parseInt(jTFIdPessoa.getText()));

            DefaultTableModel ItensFornece = (DefaultTableModel) jTitens.getModel();
            int totlinha = ItensFornece.getRowCount();
            int i = 0;
            String codIten;
            for (i = totlinha - 1; i >= 0; i--) {

                codIten = String.valueOf(ItensFornece.getValueAt(i, 0));
                prodFornece.setIDPRODUTO(Integer.parseInt(codIten));
                prodFornece.setIDFORNECEDOR(Integer.parseInt(jTFIdPessoa.getText()));
                prodFornece.setIDSEQUENCIA(i);
                prodfornecedao.incluir(prodFornece);

            }

            if (jRBFisico.isSelected()) {

                Integer id = pfisica.getIDPESSOA();
                if (id == null) {
                    pfdao.incluir(pfisica);
                }
                endDAO.incluir(endereco);
                telefoneDAO.incluir(telefone);
                fornDAO.incluir(fornecedor);
            } else {
                Integer id = pjuridica.getIDPESSOA();
                if (id == null) {
                    pjdao.incluir(pjuridica);
                }
                endDAO.incluir(endereco);
                telefoneDAO.incluir(telefone);
                fornDAO.incluir(fornecedor);
            }

            lcampos.LimparCampos(jPcadastro);
            estadobotoes(false);

        }
        
        if (situacao == 2) {
            if (jTFIdPessoa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Fornecedor");
                jTFIdPessoa.grabFocus();
                return;
            } else {
                fornecedor.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
            }

            fornecedor.setDTCADASTRO(jTFDtCadastro.getText());
            fornecedor.setTPSITUACAO(jCBTpSituação.getSelectedIndex());

            if (jTFVlLimite.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Valor Máximo de Compra");
                jTFVlLimite.grabFocus();
                return;
            } else {
                fornecedor.setVLLIMITE(Double.parseDouble(jTFVlLimite.getText()));
            }

            if (jTFemail.getText().equals("")) {
                fornecedor.setDSEMAIL("-");
                return;
            } else {
                fornecedor.setDSEMAIL(jTFemail.getText());
            }

            if (bGtipo_pessoa.isSelected(null)) {
                JOptionPane.showMessageDialog(null, "Favor selecionar o TIPO DE PESSOA!");
            } else if (jRBFisico.isSelected()) {

                pfisica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                fornecedor.setTPPESSOA("F");
                if (jTFNrCpf.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CPF");
                    jTFNrCpf.grabFocus();
                    return;
                } else {
                    pfisica.setNRCPF(jTFNrCpf.getText());
                }
                if (!jTFrg.getText().equals("")) {
                    pfisica.setNRRG(jTFrg.getText());
                }
                String sexo = jCBSexo.getSelectedItem().toString();
                if (sexo.equals("MASCULINO")) {
                    pfisica.setTPSEXO("M");
                } else {
                    pfisica.setTPSEXO("F");
                }

            } else {
                pjuridica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                fornecedor.setTPPESSOA("J");
                if (jTFNrCnpj.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CNPJ");
                    jTFNrCnpj.grabFocus();
                    return;
                } else {
                    String cnpj = jTFNrCnpj.getText();
                    pjuridica.setNRCNPJ(jTFNrCnpj.getText());

                }
                if (jTFrazaosocial.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe a Razão Social!");
                    jTFrazaosocial.grabFocus();
                    return;
                } else {
                    pjuridica.setRZSOCIAL(jTFrazaosocial.getText());
                }
            }
            if (jTFFone1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o número do Telefone");
                jTFFone1.grabFocus();
                return;
            } else {
                telefone.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                telefone.setNRFONE(jTFFone1.getText());
                telefone.setTPFONE("Comercial");
            }
            endereco.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            String cidadeId = jCBCidade.getSelectedItem().toString();
            try {
                idCidade = cidadeDAO.ConsultaIdcidade(idCidade, cidadeId);
                endereco.setIDCIDADE(idCidade);
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceCidade.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jTFlogradouro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Logradouro");
                jTFlogradouro.grabFocus();
                return;
            } else {
                endereco.setDSLOGRADOURO(jTFlogradouro.getText().toUpperCase());
            }
            if (jTFNumero.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Número do endereço");
                jTFNumero.grabFocus();
                return;
            } else {
                endereco.setDSNUMERO(jTFNumero.getText().toUpperCase());
            }
            if (jTFbairro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Bairro");
                jTFbairro.grabFocus();
                return;
            } else {
                endereco.setDSBAIRRO(jTFbairro.getText().toUpperCase());
            }
            if (jTFcomplemento.getText().equals("")) {
                endereco.setDSCOMPLEMENTO(".");
            } else {
                endereco.setDSCOMPLEMENTO(jTFcomplemento.getText());
            }
            String cep = jTFNrCep.toString();

            if (jTFNrCep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o CEP");
                jTFNrCep.grabFocus();
                return;
            } else {
                endereco.setNRCEP(jTFNrCep.getText());
            }
            endereco.setTPENDERECO("COMERCIAL");

            prodFornece.setIDFORNECEDOR(Integer.parseInt(jTFIdPessoa.getText()));

            DefaultTableModel ItensFornece = (DefaultTableModel) jTitens.getModel();
            int totlinha = ItensFornece.getRowCount();
            int i = 0;
            Boolean sel = false;
            String codIten;
            for (i = totlinha - 1; i >= 0; i--) {

                codIten = String.valueOf(ItensFornece.getValueAt(i, 0));
                prodFornece.setIDPRODUTO(Integer.parseInt(codIten));
                prodFornece.setIDFORNECEDOR(Integer.parseInt(jTFIdPessoa.getText()));
                prodFornece.setIDSEQUENCIA(i);
                prodfornecedao.alterar(prodFornece);
            }
            if (jRBFisico.isSelected()) {
                pfdao.alterar(pfisica);
                endDAO.alterar(endereco);
                telefoneDAO.alterar(telefone);
                fornDAO.alterar(fornecedor);
            } else {
                pjdao.alterar(pjuridica);
                endDAO.alterar(endereco);
                telefoneDAO.alterar(telefone);
                fornDAO.alterar(fornecedor);
            }

            lcampos.LimparCampos(jPcadastro);
            estadobotoes(false);

        }

    }//GEN-LAST:event_jBgravarActionPerformed

    private void jTFNrCepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNrCepMouseClicked

        ValidaNumero validaNumero = new ValidaNumero();
        validaNumero.ValidaNumero(jTFNrCep);
    }//GEN-LAST:event_jTFNrCepMouseClicked

    private void jTbPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbPesquisaMouseClicked

        if (evt.getClickCount() == 1) {
            int linha = jTbPesquisa.getSelectedRow();
            String ID = (String) jTbPesquisa.getValueAt(linha, 0);
            Integer idpessoa = 0;

            fornecedor.setIDPESSOA(Integer.parseInt(ID));
            fornDAO.retornadados(fornecedor);

            telefone.setIDPESSOA(Integer.parseInt(ID));
            telefoneDAO.retornadados(telefone);

            pessoa.setIDPESSOA(Integer.parseInt(ID));
            pessoaDAO.retornadados(pessoa);

            pfisica.setIDPESSOA(Integer.parseInt(ID));
            pfdao.retornadados(pfisica);

            pjuridica.setIDPESSOA(Integer.parseInt(ID));
            pjdao.retornadados(pjuridica);

            endereco.setIDPESSOA(Integer.parseInt(ID));
            endDAO.retornadados(endereco);
            
            prodFornece.setIDFORNECEDOR(Integer.parseInt(ID));
            
            

            String tpPessoa = fornecedor.getTPPESSOA();

            jTFIdPessoa.setText(Integer.toString(fornecedor.getIDPESSOA()));
            jTFemail.setText(fornecedor.getDSEMAIL());
            jTFnome.setText(pessoa.getDSPESSOA());

            if (tpPessoa.equals("F")) {
                jRBFisico.setSelected(true);

                jTFNrCnpj.setEnabled(false);
                jTFrazaosocial.setEnabled(false);

                jTFNrCpf.setText(pfisica.getNRCPF());
                jTFrg.setText(pfisica.getNRRG());
                String sexo = pfisica.getTPSEXO();
                if (sexo.equals("M")) {
                    jCBSexo.setSelectedIndex(1);
                } else {
                    jCBSexo.setSelectedIndex(0);
                }
            } else {
                jRBJuridica.setSelected(false);

                jTFNrCpf.setEnabled(false);
                jTFrg.setEnabled(false);
                jCBSexo.setEnabled(false);

                jTFrazaosocial.setText(pjuridica.getRZSOCIAL());
                jTFNrCnpj.setText(pjuridica.getNRCNPJ());
            }
            jTFDtNasc.setText(pessoa.getDTNASC());
            jTFDtCadastro.setText(fornecedor.getDTCADASTRO());
            jTFVlLimite.setText(Double.toString(fornecedor.getVLLIMITE()));
            jTFFone1.setText(telefone.getNRFONE());

            jTFlogradouro.setText(endereco.getDSLOGRADOURO());
            jTFNumero.setText(endereco.getDSNUMERO());
            jTFcomplemento.setText(endereco.getDSCOMPLEMENTO());
            jTFbairro.setText(endereco.getDSBAIRRO());
            jTFNrCep.setText(endereco.getNRCEP());

            cidadeDAO.preenchercidade(jCBCidade, cidade);

            Integer idcidade = endereco.getIDCIDADE();
            cidade.setIDCIDADE(idcidade);
            cidadeDAO.retornacidade(cidade);
            jCBCidade.setSelectedItem(cidade.getDscidade());

            PreencherJtableGenerico preencher = new PreencherJtableGenerico();
            prodfornecedao.consulta(prodFornece);
            preencher.PreencherJComboBox(jTitens, prodFornece.getRetorno());
                     
            
            }

            estadobotoes(false);
            jTPFornecedor.setSelectedIndex(0);
    }//GEN-LAST:event_jTbPesquisaMouseClicked

    
    
    private void jBtPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisa1ActionPerformed

        PreencherJtableGenerico preencher = new PreencherJtableGenerico();
        switch (jCbPesquisa2.getSelectedIndex()) {
            case 0: {
                fornDAO.consulta(fornecedor);
                preencher.PreencherJComboBox(jTbPesquisa, fornecedor.getRetorno());
                return;
            }
            case 1: {
                pessoa.setDSPESSOA(jTFPesquisa.getText().toUpperCase());
                fornDAO.consultadescricao(pessoa, fornecedor);
                preencher.PreencherJComboBox(jTbPesquisa, fornecedor.getRetorno());
                return;
            }
        }
    }//GEN-LAST:event_jBtPesquisa1ActionPerformed

    private void jTitensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTitensMouseClicked

       DefaultTableModel tabela = (DefaultTableModel) jTitens.getModel();
        int index = jTitens.getSelectedRow();
      
        String descricao = jTitens.getValueAt(index, 1).toString();
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja remover " + descricao + "?", "Remover", JOptionPane.YES_NO_OPTION);
        if (opcao == JOptionPane.YES_OPTION) {
            tabela.removeRow(index);
           
            }
        return;
    }//GEN-LAST:event_jTitensMouseClicked

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfaceFornecedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sexo;
    private javax.swing.ButtonGroup bGtipo_pessoa;
    private javax.swing.JButton jBAddProduto;
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBPesquisarPessoa;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBgravar;
    private javax.swing.JButton jBincluir;
    private javax.swing.JButton jBpesquisar;
    private javax.swing.JButton jBtPesquisa1;
    private javax.swing.JComboBox jCBCidade;
    private javax.swing.JComboBox jCBSexo;
    private javax.swing.JComboBox jCBTpSituação;
    private javax.swing.JComboBox jCbPesquisa2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPcadastro;
    private javax.swing.JPanel jPconsulta;
    private javax.swing.JPanel jPpfisica;
    private javax.swing.JPanel jPpjuridica;
    private javax.swing.JRadioButton jRBFisico;
    private javax.swing.JRadioButton jRBJuridica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCodigoItem;
    private javax.swing.JTextField jTFDsItem;
    private javax.swing.JTextField jTFDtCadastro;
    private javax.swing.JFormattedTextField jTFDtNasc;
    private javax.swing.JTextField jTFFone1;
    private javax.swing.JTextField jTFIdPessoa;
    private javax.swing.JTextField jTFNrCep;
    private javax.swing.JTextField jTFNrCnpj;
    private javax.swing.JTextField jTFNrCpf;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFPesquisa;
    private javax.swing.JTextField jTFVlLimite;
    private javax.swing.JTextField jTFbairro;
    private javax.swing.JTextField jTFcomplemento;
    private javax.swing.JTextField jTFdsproduto;
    private javax.swing.JTextField jTFemail;
    private javax.swing.JTextField jTFlogradouro;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFproduto;
    private javax.swing.JTextField jTFrazaosocial;
    private javax.swing.JTextField jTFrg;
    private javax.swing.JTabbedPane jTPFornecedor;
    private javax.swing.JTable jTbPesquisa;
    private javax.swing.JTable jTitens;
    // End of variables declaration//GEN-END:variables

    private void estadobotoes(boolean situacao) {
        jBincluir.setEnabled(!situacao);
        jBAlterar.setEnabled(!situacao);
        jBexcluir.setEnabled(!situacao);
        jBgravar.setEnabled(situacao);
        jBcancelar.setEnabled(situacao);
    }

    public void IncluirLista() {
        DefaultTableModel ItensFornece = (DefaultTableModel) jTitens.getModel();

        int totlinha = jTitens.getRowCount();
        int incluir = 0;

        if (incluir == 0) {
            ItensFornece.setNumRows(totlinha + 1);
            ItensFornece.setValueAt((jTFCodigoItem.getText()), totlinha, 0);
            ItensFornece.setValueAt((jTFDsItem.getText()), totlinha, 1);

            jTFCodigoItem.setText("");
            jTFDsItem.setText("");
        }
    }
}
