package br.tcc.Interface;

import br.tcc.Validacoes.EstadoBotoes;
import br.tcc.Validacoes.LimparCampos;
import br.tcc.Validacoes.PreencherJtableGenerico;
import br.tcc.Validacoes.RetornaDataAtual;
import br.tcc.Validacoes.ValidaNumero;
import br.tcc.classe.Cidade;
import br.tcc.classe.Cliente;
import br.tcc.classe.Endereco;
import br.tcc.classe.Pessoa;
import br.tcc.classe.PessoaFisica;
import br.tcc.classe.PessoaJuridica;
import br.tcc.classe.Telefone;
import br.tcc.dao.CidadeDAO;
import br.tcc.dao.ClienteDAO;
import br.tcc.dao.EnderecoDAO;
import br.tcc.dao.PessoaDAO;
import br.tcc.dao.PessoaFisicaDAO;
import br.tcc.dao.PessoaJuridicaDAO;
import br.tcc.dao.TelefoneDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Joao Paulo
 */
public class InterfaceCliente extends javax.swing.JFrame {
     LimparCampos lcampos = new LimparCampos();
     private int situacao = 0;
     CidadeDAO cidadeDAO = new CidadeDAO();
     RetornaDataAtual retornadata = new RetornaDataAtual();
     Cidade cidade = new Cidade();
     PessoaFisicaDAO pfDao = new PessoaFisicaDAO();
     PessoaJuridicaDAO pjDao = new PessoaJuridicaDAO();
     EnderecoDAO endDao = new EnderecoDAO();
     PessoaFisica pfisica = new PessoaFisica();
     PessoaJuridica pjuridica = new PessoaJuridica();
     Endereco endereco = new Endereco();
     Pessoa pessoa = new Pessoa();
     PessoaDAO pessoaDao = new PessoaDAO();
     Integer dig1, dig2, dig3, dig4, dig5, dig6, dig7, dig8, dig9, dig10, dig11;
     Integer dig21, dig22, dig23, dig24, dig25, dig26, dig27, dig28, dig29, dig210, dig211;
     Telefone telefone = new Telefone();
     TelefoneDAO telefoneDAO = new TelefoneDAO();
     Cliente cliente = new Cliente();
     ClienteDAO clienteDAO = new ClienteDAO();
    

    
    /** Creates new form InterfacePessoa */
    public InterfaceCliente() {
        
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGtipo_pessoa = new javax.swing.ButtonGroup();
        jTPcliente = new javax.swing.JTabbedPane();
        jPCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFIdPessoa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFnome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRBFisico = new javax.swing.JRadioButton();
        jRBJuridica = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCBCidade = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTFlogradouro = new javax.swing.JTextField();
        jTFNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFbairro = new javax.swing.JTextField();
        jTFcomplemento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFcep = new javax.swing.JTextField();
        jPpfisica = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTFrg = new javax.swing.JTextField();
        jTFcpf = new javax.swing.JTextField();
        Sexo = new javax.swing.JLabel();
        jCBSexo = new javax.swing.JComboBox();
        jPpjuridica = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFrazaosocial = new javax.swing.JTextField();
        jTFcnpj = new javax.swing.JTextField();
        jPanelbotoes = new javax.swing.JPanel();
        jBIncluir = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBgravar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBAlterar1 = new javax.swing.JButton();
        BaddPessoas = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        jTFdtnasc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTFDtCadastro = new javax.swing.JTextField();
        jBPesquisar2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jCBSituacao = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jTFFone1 = new javax.swing.JTextField();
        jPConsulta1 = new javax.swing.JPanel();
        jCbPesquisa1 = new javax.swing.JComboBox();
        jTFPesquisa1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbPesquisa1 = new javax.swing.JTable();
        jBtPesquisa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jLabel1.setText("Código");

        jLabel9.setText("Nome");

        jLabel10.setText("Data de cadastro");

        bGtipo_pessoa.add(jRBFisico);
        jRBFisico.setText("Física");
        jRBFisico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBFisicoMouseClicked(evt);
            }
        });

        bGtipo_pessoa.add(jRBJuridica);
        jRBJuridica.setText("Juridica");
        jRBJuridica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBJuridicaMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel2.setText("Cidade");

        jLabel3.setText("Logradouro");

        jLabel4.setText("Número");

        jLabel6.setText("Complemento");

        jLabel5.setText("Bairro");

        jLabel7.setText("CEP");

        jTFcep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFcepMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTFlogradouro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 131, Short.MAX_VALUE))
                            .addComponent(jTFbairro))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTFcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(146, 146, 146))
                            .addComponent(jTFcep, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFlogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPpfisica.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Física"));

        jLabel11.setText("CPF");

        jLabel12.setText("RG");

        Sexo.setText("Sexo");

        jCBSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FEMININO", "MASCULINO" }));

        javax.swing.GroupLayout jPpfisicaLayout = new javax.swing.GroupLayout(jPpfisica);
        jPpfisica.setLayout(jPpfisicaLayout);
        jPpfisicaLayout.setHorizontalGroup(
            jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpfisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTFrg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sexo)
                    .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPpfisicaLayout.setVerticalGroup(
            jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpfisicaLayout.createSequentialGroup()
                .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPpfisicaLayout.createSequentialGroup()
                        .addComponent(Sexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPpfisicaLayout.createSequentialGroup()
                        .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPpfisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );

        jPpjuridica.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoa Juridica"));

        jLabel14.setText("CNPJ");

        jLabel16.setText("Razão Social");

        javax.swing.GroupLayout jPpjuridicaLayout = new javax.swing.GroupLayout(jPpjuridica);
        jPpjuridica.setLayout(jPpjuridicaLayout);
        jPpjuridicaLayout.setHorizontalGroup(
            jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpjuridicaLayout.createSequentialGroup()
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPpjuridicaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(104, 104, 104))
                    .addGroup(jPpjuridicaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)))
        );
        jPpjuridicaLayout.setVerticalGroup(
            jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPpjuridicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPpjuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelbotoes.setBackground(new java.awt.Color(153, 153, 153));

        jBIncluir.setText("Incluir");
        jBIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncluirActionPerformed(evt);
            }
        });

        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBgravar.setText("Gravar");
        jBgravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgravarActionPerformed(evt);
            }
        });

        jBcancelar.setText("Cancelar");

        jBAlterar1.setText("Alterar");
        jBAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbotoesLayout = new javax.swing.GroupLayout(jPanelbotoes);
        jPanelbotoes.setLayout(jPanelbotoesLayout);
        jPanelbotoesLayout.setHorizontalGroup(
            jPanelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotoesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jBIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jBAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jBgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jBcancelar)
                .addGap(35, 35, 35))
        );
        jPanelbotoesLayout.setVerticalGroup(
            jPanelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotoesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelbotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        BaddPessoas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tcc/fotos/addPessoa.jpg"))); // NOI18N
        BaddPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaddPessoasActionPerformed(evt);
            }
        });

        jLabel13.setText("Data de Nascimento");

        jLabel18.setText("Tipo de Pessoa");

        jBPesquisar2.setText("Pesquisar");
        jBPesquisar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisar2MouseClicked(evt);
            }
        });
        jBPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisar2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Situação");

        jCBSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        jLabel24.setText("Telefone");

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addComponent(jPanelbotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(151, 151, 151)
                                .addComponent(jLabel9))
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBPesquisar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel18))
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addComponent(jRBFisico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBJuridica)))
                                .addGap(4, 4, 4)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFFone1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addGap(132, 132, 132)
                                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jTFdtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCBSituacao, 0, 96, Short.MAX_VALUE)
                                    .addGap(91, 91, 91)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                                .addComponent(BaddPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addComponent(jPpfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPpjuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPesquisar2)
                            .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFdtnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(26, 26, 26)))
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BaddPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRBJuridica)
                                    .addComponent(jRBFisico)))
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPpfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPpjuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelbotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPcliente.addTab("Cadastro", jPCadastro);

        jCbPesquisa1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Cliente" }));
        jCbPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbPesquisa1ActionPerformed(evt);
            }
        });

        jTbPesquisa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "Data de Cadastro", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbPesquisa1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTbPesquisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbPesquisa1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTbPesquisa1);

        jBtPesquisa1.setText("Pesquisar");
        jBtPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPConsulta1Layout = new javax.swing.GroupLayout(jPConsulta1);
        jPConsulta1.setLayout(jPConsulta1Layout);
        jPConsulta1Layout.setHorizontalGroup(
            jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsulta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPConsulta1Layout.createSequentialGroup()
                        .addComponent(jCbPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFPesquisa1)
                        .addGap(18, 18, 18)
                        .addComponent(jBtPesquisa1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPConsulta1Layout.setVerticalGroup(
            jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsulta1Layout.createSequentialGroup()
                .addGroup(jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPConsulta1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPConsulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtPesquisa1)
                            .addComponent(jTFPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPConsulta1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jCbPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPcliente.addTab("Consulta", jPConsulta1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTPcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPcliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(776, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPesquisar2ActionPerformed

    private void jBPesquisar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisar2MouseClicked
       final InterfaceRetornaPessoa retornaPessoa = new InterfaceRetornaPessoa();
        retornaPessoa.setVisible(true);
        retornaPessoa.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdPessoa.setText(retornaPessoa.retornaId);
                jTFnome.setText(retornaPessoa.retornaDsPessoa);
                jTFdtnasc.setText(retornaPessoa.retornaDtNasc);
            }
        });
                                            
    }//GEN-LAST:event_jBPesquisar2MouseClicked

    private void BaddPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaddPessoasActionPerformed
        new InterfaceRelacaoPessoa().setVisible(true);
    }//GEN-LAST:event_BaddPessoasActionPerformed

    private void jBAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterar1ActionPerformed
        situacao = 2;
        estadobotoes(true);
    }//GEN-LAST:event_jBAlterar1ActionPerformed

    private void jBgravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgravarActionPerformed
        Integer idCidade = null;
        if (situacao == 1) {
            if (jTFIdPessoa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Cliente");
                jTFIdPessoa.grabFocus();
                return;
            } else {
                cliente.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
            }

            cliente.setDTCADASTRO(jTFDtCadastro.getText());
            cliente.setTPSITUACAO(jCBSituacao.getSelectedIndex());

            telefone.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            if (jTFFone1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o número do Telefone");
                jTFFone1.grabFocus();
                return;
            } else {
                telefone.setNRFONE(jTFFone1.getText());

            }
            telefone.setTPFONE("Recado");

            if (bGtipo_pessoa.isSelected(null)) {
                JOptionPane.showMessageDialog(null, "Favor selecionar o TIPO DE Cliente!");
            } else if (jRBFisico.isSelected()) {
                pfisica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                cliente.setTPCLIENTE("F");
                if (jTFcpf.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CPF");
                    jTFcpf.grabFocus();
                    return;
                } else {
                    pfisica.setNRCPF(jTFcpf.getText());
                }
                if(!jTFrg.getText().equals("")){
                    pfisica.setNRRG(jTFrg.getText());
                }

                String sexo = jCBSexo.getSelectedItem().toString();
                if (sexo.equals("MASCULINO")) {
                    pfisica.setTPSEXO("M");
                } else {
                    pfisica.setTPSEXO("F");
                }

            } else {
                pjuridica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                cliente.setTPCLIENTE("J");
                if (jTFcnpj.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CNPJ");
                    jTFcnpj.grabFocus();
                    return;
                } else {
                    String cnpj = jTFcnpj.getText();
                    pjuridica.setNRCNPJ(jTFcnpj.getText());

                }
                if (jTFrazaosocial.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe a Razão Social!");
                    jTFrazaosocial.grabFocus();
                    return;
                } else {
                    pjuridica.setRZSOCIAL(jTFrazaosocial.getText());
                }
            }
            endereco.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            String cidadeId = jCBCidade.getSelectedItem().toString();
            try {
                idCidade = cidadeDAO.ConsultaIdcidade(idCidade, cidadeId);
                endereco.setIDCIDADE(idCidade);
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceCidade.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jTFlogradouro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Logradouro");
                jTFlogradouro.grabFocus();
                return;
            } else {
                endereco.setDSLOGRADOURO(jTFlogradouro.getText().toUpperCase());
            }
            if (jTFNumero.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Número do endereço");
                jTFNumero.grabFocus();
                return;
            } else {
                endereco.setDSNUMERO(jTFNumero.getText().toUpperCase());
            }
            if (jTFbairro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Bairro");
                jTFbairro.grabFocus();
                return;
            } else {
                endereco.setDSBAIRRO(jTFbairro.getText().toUpperCase());
            }
            if (jTFcomplemento.getText().equals("")) {
                endereco.setDSCOMPLEMENTO(".");
            } else {
                endereco.setDSCOMPLEMENTO(jTFcomplemento.getText());
            }
            String cep = jTFcep.toString();

            if (jTFcep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o CEP");
                jTFcep.grabFocus();
                return;
            } else {
                endereco.setNRCEP(jTFcep.getText());
            }
            endereco.setTPENDERECO("CLIENTE");
            if (jRBFisico.isSelected()) {
                
                Integer id = pfisica.getIDPESSOA();
                if (id == null) {
                    pfDao.incluir(pfisica);
                }
                
                endDao.incluir(endereco);
                telefoneDAO.incluir(telefone);
                clienteDAO.incluir(cliente);
            } else {
                Integer id = pjuridica.getIDPESSOA();
                if (id == null) {
                    pjDao.incluir(pjuridica);
                }
              
                endDao.incluir(endereco);
                telefoneDAO.incluir(telefone);
                clienteDAO.incluir(cliente);
            }

            lcampos.LimparCampos(jTPcliente);
            estadobotoes(false);

        } else{
             if (jTFIdPessoa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Cliente");
                jTFIdPessoa.grabFocus();
                return;
            } else {
                cliente.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
            }
             
             if (jTFnome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe nome do Cliente");
                jTFnome.grabFocus();
                return;
            } else {
                pessoa.setDSPESSOA(jTFnome.getText());
            }

            cliente.setDTCADASTRO(jTFDtCadastro.getText());
            cliente.setTPSITUACAO(jCBSituacao.getSelectedIndex());

            telefone.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            if (jTFFone1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o número do Telefone");
                jTFFone1.grabFocus();
                return;
            } else {
                telefone.setNRFONE(jTFFone1.getText());

            }
            telefone.setTPFONE("Principal");

            if (bGtipo_pessoa.isSelected(null)) {
                JOptionPane.showMessageDialog(null, "Favor selecionar o TIPO DE Cliente!");
            } else if (jRBFisico.isSelected()) {
                pfisica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                cliente.setTPCLIENTE("F");
                if (jTFcpf.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CPF");
                    jTFcpf.grabFocus();
                    return;
                } else {
                    pfisica.setNRCPF(jTFcpf.getText());
                }
                if(!jTFrg.getText().equals("")){
                    pfisica.setNRRG(jTFrg.getText());
                }

                String sexo = jCBSexo.getSelectedItem().toString();
                if (sexo.equals("MASCULINO")) {
                    pfisica.setTPSEXO("M");
                } else {
                    pfisica.setTPSEXO("F");
                }

            } else {
                pjuridica.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
                cliente.setTPCLIENTE("J");
                if (jTFcnpj.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe o número do CNPJ");
                    jTFcnpj.grabFocus();
                    return;
                } else {
                    String cnpj = jTFcnpj.getText();
                    pjuridica.setNRCNPJ(jTFcnpj.getText());

                }
                if (jTFrazaosocial.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe a Razão Social!");
                    jTFrazaosocial.grabFocus();
                    return;
                } else {
                    pjuridica.setRZSOCIAL(jTFrazaosocial.getText());
                }
            }
            endereco.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));

            String cidadeId = jCBCidade.getSelectedItem().toString();
            try {
                idCidade = cidadeDAO.ConsultaIdcidade(idCidade, cidadeId);
                endereco.setIDCIDADE(idCidade);
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceCidade.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (jTFlogradouro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Logradouro");
                jTFlogradouro.grabFocus();
                return;
            } else {
                endereco.setDSLOGRADOURO(jTFlogradouro.getText().toUpperCase());
            }
            if (jTFNumero.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Número do endereço");
                jTFNumero.grabFocus();
                return;
            } else {
                endereco.setDSNUMERO(jTFNumero.getText().toUpperCase());
            }
            if (jTFbairro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Bairro");
                jTFbairro.grabFocus();
                return;
            } else {
                endereco.setDSBAIRRO(jTFbairro.getText().toUpperCase());
            }
            if (jTFcomplemento.getText().equals("")) {
                endereco.setDSCOMPLEMENTO(".");
            } else {
                endereco.setDSCOMPLEMENTO(jTFcomplemento.getText());
            }
            String cep = jTFcep.toString();

            if (jTFcep.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o CEP");
                jTFcep.grabFocus();
                return;
            } else {
                endereco.setNRCEP(jTFcep.getText());
            }
            endereco.setTPENDERECO("CLIENTE");
            

            if (jRBFisico.isSelected()) {
                pfDao.alterar(pfisica);
                endDao.alterar(endereco);
                telefoneDAO.alterar(telefone);
                clienteDAO.alterar(cliente);
            } else {
                pjDao.alterar(pjuridica);
                endDao.alterar(endereco);
                telefoneDAO.alterar(telefone);
                clienteDAO.alterar(cliente);
            }
            lcampos.LimparCampos(jTPcliente);
            estadobotoes(false);

        }
    }//GEN-LAST:event_jBgravarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        situacao = 1;
        
        int t = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente EXCLUIR o registro?");
        if (t == 0) {    
                endDao.excluir(endereco);
                telefoneDAO.excluir(telefone);
                clienteDAO.excluir(cliente);
            }
            JOptionPane.showMessageDialog(rootPane, "Registro excluido com sucesso!");
            estadobotoes(false);
            lcampos.LimparCampos(jTPcliente);
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncluirActionPerformed
        jTFdtnasc.grabFocus();
        lcampos.LimparCampos(jTPcliente);
        situacao = 1;
        estadobotoes(true);
        cidadeDAO.preenchercidade(jCBCidade, cidade);
        retornadata.RetornaDataAtual(jTFDtCadastro);
        
    }//GEN-LAST:event_jBIncluirActionPerformed

    private void jTFcepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFcepMouseClicked

        ValidaNumero validaNumero = new ValidaNumero();
        validaNumero.ValidaNumero(jTFcep);
    }//GEN-LAST:event_jTFcepMouseClicked

    private void jRBJuridicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBJuridicaMouseClicked
        jTFcpf.setEnabled(false);
        jTFrg.setEnabled(false);
        jCBSexo.setEnabled(false);

        jTFcnpj.setEnabled(true);
        jTFrazaosocial.setEnabled(true);

        String ID = jTFIdPessoa.getText();

        pjuridica.setIDPESSOA(Integer.parseInt(ID));
        pjDao.retornadados(pjuridica);
        jTFcnpj.setText(pjuridica.getNRCNPJ());
        jTFrazaosocial.setText(pjuridica.getRZSOCIAL());
    }//GEN-LAST:event_jRBJuridicaMouseClicked

    private void jRBFisicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBFisicoMouseClicked

        jTFcpf.setEnabled(true);
        jTFrg.setEnabled(true);
        jCBSexo.setEnabled(true);

        jTFcnpj.setEnabled(false);
        jTFrazaosocial.setEnabled(false);

        String ID = jTFIdPessoa.getText();

        pfisica.setIDPESSOA(Integer.parseInt(ID));
        pfDao.retornadados(pfisica);
        jTFcpf.setText(pfisica.getNRCPF());
        jTFrg.setText(pfisica.getNRRG());
        String sexo = pfisica.getTPSEXO();

        if (sexo.equals("M")) {
            jCBSexo.setSelectedItem("MASCULINO");
        } else {
            jCBSexo.setSelectedItem("FEMININO");
        }

    }//GEN-LAST:event_jRBFisicoMouseClicked

    private void jCbPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbPesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbPesquisa1ActionPerformed

    private void jBtPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisa1ActionPerformed
       
        PreencherJtableGenerico preencher = new PreencherJtableGenerico();
        switch (jCbPesquisa1.getSelectedIndex()) {
            case 0: {
                clienteDAO.consulta(cliente);
                preencher.PreencherJComboBox(jTbPesquisa1, cliente.getRetorno());
                return;
            }
            case 1: {
                pessoa.setDSPESSOA(jTFPesquisa1.getText().toUpperCase());
                clienteDAO.consultadescricao(pessoa, cliente);
                preencher.PreencherJComboBox(jTbPesquisa1, cliente.getRetorno());
                return;
            }
        }
    }//GEN-LAST:event_jBtPesquisa1ActionPerformed

    private void jTbPesquisa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbPesquisa1MouseClicked
          if(evt.getClickCount() == 1){
            int linha = jTbPesquisa1.getSelectedRow();
            String ID = (String) jTbPesquisa1.getValueAt(linha, 0);
            Integer idpessoa = 0;
            
            cliente.setIDPESSOA(Integer.parseInt(ID));
            clienteDAO.retornadados(cliente);
           
            telefone.setIDPESSOA(Integer.parseInt(ID));
            telefoneDAO.retornadados(telefone);
            
            pessoa.setIDPESSOA(Integer.parseInt(ID));
            pessoaDao.retornadados(pessoa);
            
            pfisica.setIDPESSOA(Integer.parseInt(ID));
            pfDao.retornadados(pfisica);
            
            pjuridica.setIDPESSOA(Integer.parseInt(ID));
            pjDao.retornadados(pjuridica);
            
            endereco.setIDPESSOA(Integer.parseInt(ID));
            endDao.retornadados(endereco);
            
            String tpPessoa = cliente.getTPCLIENTE();
            Integer tpSituacao = cliente.getTPSITUACAO();
            
            jTFIdPessoa.setText(Integer.toString(cliente.getIDPESSOA()));
            jTFnome.setText(pessoa.getDSPESSOA());
            
            jCBSituacao.setSelectedIndex(tpSituacao);
            
            if (tpPessoa.equals("F")){
                jRBFisico.setSelected(true);
                
                 jTFcnpj.setEnabled(false);
                 jTFrazaosocial.setEnabled(false);
                 
                 jTFcpf.setText(pfisica.getNRCPF());
                 jTFrg.setText(pfisica.getNRRG());
                 String sexo = pfisica.getTPSEXO();
                 if(sexo.equals("M")){
                     jCBSexo.setSelectedIndex(1);
                 }else{
                     jCBSexo.setSelectedIndex(0);
                 }             
                 
            }else{
                jRBJuridica.setSelected(false);
                
                jTFcpf.setEnabled(false);
                jTFrg.setEnabled(false);
                jCBSexo.setEnabled(false);
                
                jTFrazaosocial.setText(pjuridica.getRZSOCIAL());
                jTFcnpj.setText(pjuridica.getNRCNPJ());
            }
            jTFdtnasc.setText(pessoa.getDTNASC());
            jTFDtCadastro.setText(cliente.getDTCADASTRO());
            jTFFone1.setText(telefone.getNRFONE());
           
            
            jTFlogradouro.setText(endereco.getDSLOGRADOURO());
            jTFNumero.setText(endereco.getDSNUMERO());
            jTFcomplemento.setText(endereco.getDSCOMPLEMENTO());
            jTFbairro.setText(endereco.getDSBAIRRO());
            jTFcep.setText(endereco.getNRCEP());
            
            cidadeDAO.preenchercidade(jCBCidade, cidade);
            
            Integer idcidade = endereco.getIDCIDADE();
            cidade.setIDCIDADE(idcidade);
            cidadeDAO.retornacidade(cidade);
            jCBCidade.setSelectedItem(cidade.getDscidade());             
           
        }
       
        estadobotoes(false);
        jTPcliente.setSelectedIndex(0);
    }//GEN-LAST:event_jTbPesquisa1MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new InterfaceCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BaddPessoas;
    private javax.swing.JLabel Sexo;
    private javax.swing.ButtonGroup bGtipo_pessoa;
    private javax.swing.JButton jBAlterar1;
    private javax.swing.JButton jBIncluir;
    private javax.swing.JButton jBPesquisar2;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBgravar;
    private javax.swing.JButton jBtPesquisa1;
    private javax.swing.JComboBox jCBCidade;
    private javax.swing.JComboBox jCBSexo;
    private javax.swing.JComboBox<String> jCBSituacao;
    private javax.swing.JComboBox jCbPesquisa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPConsulta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelbotoes;
    private javax.swing.JPanel jPpfisica;
    private javax.swing.JPanel jPpjuridica;
    private javax.swing.JRadioButton jRBFisico;
    private javax.swing.JRadioButton jRBJuridica;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFDtCadastro;
    private javax.swing.JTextField jTFFone1;
    private javax.swing.JTextField jTFIdPessoa;
    private javax.swing.JTextField jTFNumero;
    private javax.swing.JTextField jTFPesquisa1;
    private javax.swing.JTextField jTFbairro;
    private javax.swing.JTextField jTFcep;
    private javax.swing.JTextField jTFcnpj;
    private javax.swing.JTextField jTFcomplemento;
    private javax.swing.JTextField jTFcpf;
    private javax.swing.JTextField jTFdtnasc;
    private javax.swing.JTextField jTFlogradouro;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTextField jTFrazaosocial;
    private javax.swing.JTextField jTFrg;
    private javax.swing.JTabbedPane jTPcliente;
    private javax.swing.JTable jTbPesquisa1;
    // End of variables declaration//GEN-END:variables

    private void estadobotoes(boolean situacao) {
        jBIncluir.setEnabled(!situacao);
        jBAlterar1.setEnabled(!situacao);
        jBexcluir.setEnabled(!situacao);
        jBgravar.setEnabled(situacao);
        jBcancelar.setEnabled(situacao);
    }
}

