package br.tcc.Interface;

import br.tcc.ConsultaSimples.ConsultaCliente;
import br.tcc.ConsultaSimples.ConsultaFormaPgto;
import br.tcc.ConsultaSimples.ConsultaFornecedor;
import br.tcc.ConsultaSimples.ConsultaProduto;
import br.tcc.Validacoes.LimparCampos;
import br.tcc.Validacoes.RetornaDataAtual;
import br.tcc.classe.Compra;
import br.tcc.classe.ItensCompra;
import br.tcc.classe.TipoMovto;
import br.tcc.dao.CompraDAO;
import br.tcc.dao.ItensCompraDAO;
import br.tcc.dao.TpMovtoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOÃO PAULO
 */
public class InterfaceCompraVenda extends javax.swing.JFrame {
    
    LimparCampos lcampos = new LimparCampos();
    Integer situacao = 0;
    TpMovtoDAO tpMovtoDAO = new TpMovtoDAO();
    TipoMovto tpMovto = new TipoMovto();
    RetornaDataAtual retornadata = new RetornaDataAtual();
    Compra compra = new Compra();
    CompraDAO compraDAO = new CompraDAO();
    ItensCompra itensCompra = new ItensCompra();
    ItensCompraDAO itensCompraDAO = new ItensCompraDAO();

    /**
     * Creates new form InterfaceVenda
     */
    public InterfaceCompraVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jFTFdt_cadastro = new javax.swing.JFormattedTextField();
        jPanelbotoes1 = new javax.swing.JPanel();
        jBincluir1 = new javax.swing.JButton();
        jBAlterar1 = new javax.swing.JButton();
        jBexcluir1 = new javax.swing.JButton();
        jBgravar1 = new javax.swing.JButton();
        jBcancelar1 = new javax.swing.JButton();
        jTPVenda = new javax.swing.JTabbedPane();
        jPCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFIdVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFIdCliente = new javax.swing.JTextField();
        jBPesquisarCliente = new javax.swing.JButton();
        jTFDsCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCBTpMovto = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTFIdProduto = new javax.swing.JTextField();
        jBPesquisarProduto = new javax.swing.JButton();
        jTFDsProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFVlProduto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTFVlTotal = new javax.swing.JTextField();
        jBAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVenda = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTFVlTotalVenda = new javax.swing.JTextField();
        jPanelbotoes2 = new javax.swing.JPanel();
        jBIncluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBGravar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTFIdFornecedor = new javax.swing.JTextField();
        jBPesquisarfornecedor = new javax.swing.JButton();
        jTFDsfornecedor = new javax.swing.JTextField();
        jTFIdFormaPgto = new javax.swing.JTextField();
        jBPesquisarfornecedor1 = new javax.swing.JButton();
        jTFDsforma = new javax.swing.JTextField();
        jTFData = new javax.swing.JTextField();
        jPConsulta = new javax.swing.JPanel();

        jLabel5.setText("Data de Alteração");

        try {
            jFTFdt_cadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanelbotoes1.setBackground(new java.awt.Color(153, 153, 153));

        jBincluir1.setText("Incluir");
        jBincluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincluir1ActionPerformed(evt);
            }
        });

        jBAlterar1.setText("Alterar");

        jBexcluir1.setText("Excluir");

        jBgravar1.setText("Gravar");
        jBgravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgravar1ActionPerformed(evt);
            }
        });

        jBcancelar1.setText("Cancelar");

        javax.swing.GroupLayout jPanelbotoes1Layout = new javax.swing.GroupLayout(jPanelbotoes1);
        jPanelbotoes1.setLayout(jPanelbotoes1Layout);
        jPanelbotoes1Layout.setHorizontalGroup(
            jPanelbotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotoes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBincluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jBexcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBgravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBcancelar1)
                .addContainerGap())
        );
        jPanelbotoes1Layout.setVerticalGroup(
            jPanelbotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotoes1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelbotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBincluir1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jBAlterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBexcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBgravar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");

        jTPVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTPVendaFocusLost(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("Cliente");

        jBPesquisarCliente.setText("Pesquisar");
        jBPesquisarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarClienteMouseClicked(evt);
            }
        });

        jLabel3.setText("Tipo de Movimento");

        jLabel4.setText("Forma Pgto");

        jCBTpMovto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o Tipo de Movimento" }));

        jLabel6.setText("Data de Venda");

        jLabel12.setText("Codigo do Produto");

        jBPesquisarProduto.setText("Pesquisar");
        jBPesquisarProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarProdutoMouseClicked(evt);
            }
        });

        jLabel11.setText("Valor da unidade");

        jLabel13.setText("Quantidade");

        jTFQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFQuantidadeFocusLost(evt);
            }
        });

        jLabel14.setText("Valor Total");

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jTVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Valor", "Quantidade", "Valor total"
            }
        ));
        jScrollPane1.setViewportView(jTVenda);

        jLabel15.setText("Valor total");

        jPanelbotoes2.setBackground(new java.awt.Color(153, 153, 153));
        jPanelbotoes2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBIncluir.setText("Incluir");
        jBIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncluirActionPerformed(evt);
            }
        });
        jPanelbotoes2.add(jBIncluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 20, 70, 30));

        jBAlterar.setText("Alterar");
        jBAlterar.setMaximumSize(new java.awt.Dimension(65, 30));
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });
        jPanelbotoes2.add(jBAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 70, 30));

        jBExcluir.setText("Excluir");
        jPanelbotoes2.add(jBExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 20, 70, 30));

        jBGravar.setText("Concluir");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });
        jPanelbotoes2.add(jBGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 20, 80, 30));

        jBCancelar.setText("Cancelar");
        jPanelbotoes2.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 20, -1, 30));

        jLabel16.setText("Fornecedor");

        jBPesquisarfornecedor.setText("Pesquisar");
        jBPesquisarfornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarfornecedorMouseClicked(evt);
            }
        });

        jBPesquisarfornecedor1.setText("Pesquisar");
        jBPesquisarfornecedor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarfornecedor1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelbotoes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFIdFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPesquisarfornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDsfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFVlTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTFIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTFIdCliente)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addComponent(jBPesquisarCliente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTFDsCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCBTpMovto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFVlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBAdicionar)
                                    .addGap(41, 41, 41))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFIdFormaPgto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBPesquisarfornecedor1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFDsforma, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBPesquisarProduto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFDsProduto))))))
                .addGap(37, 37, 37))
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jCBTpMovto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarCliente)
                    .addComponent(jTFDsCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTFIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarfornecedor)
                    .addComponent(jTFDsfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIdFormaPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarfornecedor1)
                    .addComponent(jTFDsforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarProduto)
                    .addComponent(jTFDsProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTFVlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTFVlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTFVlTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelbotoes2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTPVenda.addTab("Cadastro", jPCadastro);

        javax.swing.GroupLayout jPConsultaLayout = new javax.swing.GroupLayout(jPConsulta);
        jPConsulta.setLayout(jPConsultaLayout);
        jPConsultaLayout.setHorizontalGroup(
            jPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPConsultaLayout.setVerticalGroup(
            jPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTPVenda.addTab("Consulta", jPConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTPVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(714, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBincluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincluir1ActionPerformed

    }//GEN-LAST:event_jBincluir1ActionPerformed

    private void jBgravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgravar1ActionPerformed

    }//GEN-LAST:event_jBgravar1ActionPerformed

    private void jBIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncluirActionPerformed

        lcampos.LimparCampos(jTPVenda);
        situacao = 1;
        estadobotoes(true);
        tpMovtoDAO.preencherTpmovimento(jCBTpMovto, tpMovto);
        retornadata.RetornaDataAtual(jTFData);
        jTFVlTotalVenda.setText("0.0");
    }//GEN-LAST:event_jBIncluirActionPerformed

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed

        tpMovto.setDSMVTO(jCBTpMovto.getSelectedItem().toString());
        tpMovtoDAO.VerificarOperacao(tpMovto);
        
        if(!tpMovto.getTPMOVTO().toString().equals("E")){
            jTFIdFornecedor.setEnabled(false);
            jTFDsfornecedor.setEnabled(false);
            
        }else{
            jTFIdCliente.setEnabled(false);
            jTFDsCliente.setEnabled(false);
                        
            if(jTFIdFornecedor.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Código do Fornecedor é obrigatório");
            }else{
                compra.setIDFORNECEDOR(Integer.parseInt(jTFIdFornecedor.getText()));
            }
            if(jTFData.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Data é um campo obrigatório");
            }else{
                compra.setDTVENDA(jTFData.getText());
            }
            if(jTFIdFormaPgto.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Código da Forma de Pagamento é Obrigatório");
            }else{
                compra.setIDFORMAPGTO(Integer.parseInt(jTFIdFormaPgto.getText()));
            }
            compraDAO.incluir(compra);
            
            
            Integer idV = null;
            try {
                idV = compraDAO.retornaUltimoId(idV);
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceCompraVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
                    int totlinha = jTVenda.getRowCount();
                    int conta = 0;
                    for (int i = 1; i <= totlinha; i++) {
                        String IdProd = (String) jTVenda.getValueAt(conta, 0);
                        String vlProduto = (String) jTVenda.getValueAt(conta, 2);
                        String QtdProd = (String) jTVenda.getValueAt(conta, 3);
                        itensCompra.setIDCOMPRA(idV);
                        itensCompra.setIDPRODUTO(Integer.parseInt(IdProd));
                        itensCompra.setVLPRODUTO(Double.parseDouble(vlProduto));
                        itensCompra.setQTDPRODUTO(Integer.parseInt(QtdProd));                       
                        conta = conta + 1;
                        itensCompraDAO.incluir(itensCompra);
                    }
                    
                    
                    
            
            lcampos.LimparCampos(jPCadastro);
        }
        
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBPesquisarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarClienteMouseClicked
        final ConsultaCliente  retornaCliente = new ConsultaCliente();
        retornaCliente.setVisible(true);
        retornaCliente.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdCliente.setText(retornaCliente.retornaId);
                jTFDsCliente.setText(retornaCliente.retornaDsCliente);
            }
        });
    }//GEN-LAST:event_jBPesquisarClienteMouseClicked

    private void jBPesquisarProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarProdutoMouseClicked
       final ConsultaProduto  retornaProduto = new ConsultaProduto();
        retornaProduto.setVisible(true);
        retornaProduto.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdProduto.setText(retornaProduto.retornaId);
                jTFDsProduto.setText(retornaProduto.retornaDsProduto);
            }
        });
    }//GEN-LAST:event_jBPesquisarProdutoMouseClicked

    private void jBPesquisarfornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarfornecedorMouseClicked
        
        final ConsultaFornecedor  retornaFornecedor = new ConsultaFornecedor();
        retornaFornecedor.setVisible(true);
        retornaFornecedor.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdFornecedor.setText(retornaFornecedor.retornaId);
                jTFDsfornecedor.setText(retornaFornecedor.retornaDsFornecedor);
            }
        });
    }//GEN-LAST:event_jBPesquisarfornecedorMouseClicked

    private void jBPesquisarfornecedor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarfornecedor1MouseClicked
      final ConsultaFormaPgto  retornaPgto = new ConsultaFormaPgto();
        retornaPgto.setVisible(true);
        retornaPgto.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdFormaPgto.setText(retornaPgto.retornaId);
                jTFDsforma.setText(retornaPgto.retornaDsForma);
            }
        });
    }//GEN-LAST:event_jBPesquisarfornecedor1MouseClicked

    private void jTFQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFQuantidadeFocusLost
        Double preco = 0.0;
        int qtd= 0;
        
        preco = Double.parseDouble(jTFVlProduto.getText());
        qtd = Integer.parseInt(jTFQuantidade.getText());
        
        jTFVlTotal.setText(String.valueOf(preco * qtd));        
    }//GEN-LAST:event_jTFQuantidadeFocusLost

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed

        if (!jTFIdProduto.getText().equals("")) {
            if (!jTFDsProduto.getText().equals("")) {
                if (!jTFVlProduto.getText().equals("")) {
                    if(!jTFQuantidade.getText().equals("")){
                        IncluirLista();
                    }else{
                        JOptionPane.showMessageDialog(null, "Informe a Quantidade de produtos a ser comprados!");
                    jTFQuantidade.grabFocus();
                    }
                }else {
                    JOptionPane.showMessageDialog(null, "Valor do Produto não encontrado");
                    jTFVlProduto.grabFocus();
                }
            }else {
                    JOptionPane.showMessageDialog(null, "Informe o nome do produto!");
                    jTFDsProduto.grabFocus();
                }
        }else {
                    JOptionPane.showMessageDialog(null, "Informe o codigo do produto!");
                    jTFIdProduto.grabFocus();
                }
         
        

    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jTPVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTPVendaFocusLost
        
        tpMovto.setDSMVTO(jCBTpMovto.getSelectedItem().toString());
        tpMovtoDAO.VerificarOperacao(tpMovto);
        
        if(tpMovto.getTPMOVTO().toString().equals("E")){
            jTFIdCliente.setEnabled(false);
            jTFDsCliente.setEnabled(false);
            
        }else{
            jTFIdFornecedor.setEnabled(false);
            jTFDsfornecedor.setEnabled(false);
           }
    }//GEN-LAST:event_jTPVendaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCompraVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCompraVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCompraVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCompraVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCompraVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBAlterar1;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jBIncluir;
    private javax.swing.JButton jBPesquisarCliente;
    private javax.swing.JButton jBPesquisarProduto;
    private javax.swing.JButton jBPesquisarfornecedor;
    private javax.swing.JButton jBPesquisarfornecedor1;
    private javax.swing.JButton jBcancelar1;
    private javax.swing.JButton jBexcluir1;
    private javax.swing.JButton jBgravar1;
    private javax.swing.JButton jBincluir1;
    private javax.swing.JComboBox jCBTpMovto;
    private javax.swing.JFormattedTextField jFTFdt_cadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPConsulta;
    private javax.swing.JPanel jPanelbotoes1;
    private javax.swing.JPanel jPanelbotoes2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFData;
    private javax.swing.JTextField jTFDsCliente;
    private javax.swing.JTextField jTFDsProduto;
    private javax.swing.JTextField jTFDsforma;
    private javax.swing.JTextField jTFDsfornecedor;
    private javax.swing.JTextField jTFIdCliente;
    private javax.swing.JTextField jTFIdFormaPgto;
    private javax.swing.JTextField jTFIdFornecedor;
    private javax.swing.JTextField jTFIdProduto;
    private javax.swing.JTextField jTFIdVenda;
    private javax.swing.JTextField jTFQuantidade;
    private javax.swing.JTextField jTFVlProduto;
    private javax.swing.JTextField jTFVlTotal;
    private javax.swing.JTextField jTFVlTotalVenda;
    private javax.swing.JTabbedPane jTPVenda;
    private javax.swing.JTable jTVenda;
    // End of variables declaration//GEN-END:variables

     private void estadobotoes(boolean situacao) {
        jBIncluir.setEnabled(!situacao);
        jBAlterar.setEnabled(!situacao);
        jBExcluir.setEnabled(!situacao);
        jBGravar.setEnabled(situacao);
        jBCancelar.setEnabled(situacao);
    }

    private void IncluirLista() {
   
        DefaultTableModel ItensFornece = (DefaultTableModel) jTVenda.getModel();
        int totlinha = jTVenda.getRowCount();
        int incluir = 0;
        int conta = 0;
        int linha = 0;
                
        for (int i = 1; i <= totlinha; i++) {
            String IdProd = (String) jTVenda.getValueAt(conta, 0);

            if (jTFIdProduto.getText().equals(IdProd)) {
                int opcao_escolhida = JOptionPane.showConfirmDialog(null, "Produto ja"
                        + " foi incluido, deseja alterar quantidade? ", "Alteração ",
                        JOptionPane.YES_NO_OPTION);

                if (opcao_escolhida == JOptionPane.YES_OPTION) {
                    incluir = 1; 
                    linha = conta;
                } else {
                    return;
                }
            }
            conta = conta + 1;
        }
        
        if (incluir == 0) {
            Double totalVenda = Double.parseDouble(jTFVlTotalVenda.getText());
            Double vltotal = Double.parseDouble(jTFVlTotal.getText());
            String soma = String.valueOf(totalVenda + vltotal);
            jTFVlTotalVenda.setText(soma);
            
            ItensFornece.setNumRows(totlinha + 1);
            ItensFornece.setValueAt(jTFIdProduto.getText(), totlinha, 0);
            ItensFornece.setValueAt(jTFDsProduto.getText(), totlinha, 1);
            ItensFornece.setValueAt(jTFVlProduto.getText(), totlinha, 2);
            ItensFornece.setValueAt(jTFQuantidade.getText(), totlinha, 3);
            ItensFornece.setValueAt(jTFVlTotal.getText(), totlinha, 4);

            jTFIdProduto.setText("");
            jTFDsProduto.setText("");
            jTFVlProduto.setText("");
            jTFQuantidade.setText("");
            jTFVlTotal.setText("");
        }
        
        else if (incluir == 1) {
        
            Double totalVenda = Double.parseDouble(jTFVlTotalVenda.getText());
            Double vltotal = Double.parseDouble(jTFVlTotal.getText());
            String soma = String.valueOf(totalVenda + vltotal);
            jTFVlTotalVenda.setText(soma);
            
            String quantidade = (String) jTVenda.getValueAt(linha, 3);
            String vltot = (String) jTVenda.getValueAt(linha, 4);
            
            Integer quantidadeAtual = Integer.parseInt(quantidade) + Integer.parseInt(jTFQuantidade.getText());
            Double vltotalAtual = Double.parseDouble(vltot) + Double.parseDouble(jTFVlTotal.getText());
            
            jTVenda.setValueAt(quantidadeAtual, linha, 3);
            jTVenda.setValueAt(vltotalAtual, linha, 4);

            jTFIdProduto.setText("");
            jTFDsProduto.setText("");
            jTFQuantidade.setText("");
            jTFVlTotal.setText("");
            jTFVlProduto.setText("");

        }
    }
}
