/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.tcc.Interface;

import br.tcc.Validacoes.LimparCampos;
import br.tcc.Validacoes.PreencherJtableGenerico;
import br.tcc.classe.Funcionario;
import br.tcc.classe.Telefone;
import br.tcc.dao.PessoaDAO;
import br.tcc.dao.TelefoneDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author JOÃO PAULO
 */
public class InterfaceTelefone extends javax.swing.JFrame {
    
    Telefone telefone = new Telefone();
    TelefoneDAO telefoneDAO = new TelefoneDAO();
    Funcionario funcionario = new Funcionario();
    LimparCampos lcampos = new LimparCampos();
    PessoaDAO pessoaDAO = new PessoaDAO();

    /**
     * Creates new form InterfaceTelefone
     */
    public InterfaceTelefone() {
        initComponents();
        atualizatabela();
    }
    
    public void CapturaIdPessoa(String IdPessoa) throws SQLException{
        jTFIdPessoa.setText(IdPessoa);
        capturaDsPessoa(IdPessoa);
    }
    
    public void capturaDsPessoa(String IdPessoa) throws SQLException{
         String DsPessoa = null;
        String pessoa = null;
        Integer Idpessoas = Integer.parseInt(IdPessoa);
        
        pessoa = pessoaDAO.consultarPEssoa(Idpessoas, DsPessoa);
        jTFNome.setText(pessoa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTelefone = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFFone = new javax.swing.JTextField();
        jBAdicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCBTipo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTelefone = new javax.swing.JTable();
        jBVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFIdPessoa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Telefone");

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Principal", "Casa", "Celular 1", "Celular 2", "Trabalho", "Recado" }));

        jTTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo", "Numero"
            }
        ));
        jScrollPane1.setViewportView(jTTelefone);

        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        jLabel4.setText("Código");

        javax.swing.GroupLayout jPTelefoneLayout = new javax.swing.GroupLayout(jPTelefone);
        jPTelefone.setLayout(jPTelefoneLayout);
        jPTelefoneLayout.setHorizontalGroup(
            jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addGroup(jPTelefoneLayout.createSequentialGroup()
                        .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPTelefoneLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCBTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPTelefoneLayout.createSequentialGroup()
                                .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBAdicionar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelefoneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBVoltar))
                    .addGroup(jPTelefoneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNome)))
                .addContainerGap())
        );
        jPTelefoneLayout.setVerticalGroup(
            jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPTelefoneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBAdicionar)
                        .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
      
        Integer idTpFone = null;
        telefone.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
        telefone.setTPFONE(jCBTipo.getSelectedIndex());
        if (jTFFone.getText().length() < 8){
            JOptionPane.showMessageDialog(null, "Informe o numeno do telefone valido!");
             jTFFone.grabFocus();
        }else{
            telefone.setNRFONE(jTFFone.getText());
        }
        if(jTFFone.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o numeno do telefone");
            jTFFone.grabFocus();
            return;
        }
        telefoneDAO.incluir(telefone);
        JOptionPane.showMessageDialog(null, "Telefone Cadastrado com Sucesso!");
        lcampos.LimparCampos(jPTelefone);
        atualizatabela();
        
        
       
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        InterfaceFuncionario Infun = new InterfaceFuncionario();
       
        Infun.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBVoltarActionPerformed

       private void atualizatabela() {
           PreencherJtableGenerico preencher = new PreencherJtableGenerico();
           telefoneDAO.consulta(telefone);
           preencher.PreencherJComboBox(jTTelefone, telefone.getRetorno());
           return;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceTelefone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox jCBTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFone;
    private javax.swing.JTextField jTFIdPessoa;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTable jTTelefone;
    // End of variables declaration//GEN-END:variables

 
}
