package br.tcc.Interface;

import br.tcc.Validacoes.LimparCampos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOÃO PAULO
 */
public class InterfaceRelacaoPessoa extends javax.swing.JFrame {

    LimparCampos lcampos = new LimparCampos();
    Integer situacao = 0;

    /**
     * Creates new form Cliente
     */
    public InterfaceRelacaoPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPRelacaoCliente = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTFIdPessoa = new javax.swing.JTextField();
        jTFnome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTrelacao = new javax.swing.JTable();
        jPBotoes = new javax.swing.JPanel();
        jBAdicionar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBGravar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBAdd = new javax.swing.JButton();
        jCBcomemoracao = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTFNomerelacao = new javax.swing.JTextField();
        jTFTpAmizade = new javax.swing.JTextField();
        jBPesquisar2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTFData = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jPRelacaoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Pessoas"));

        jLabel18.setText("Codigo");

        jTrelacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Comemoração", "Data", "Tipo Amizade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTrelacao);

        jPBotoes.setBackground(new java.awt.Color(102, 102, 102));
        jPBotoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 45, 5));

        jBAdicionar.setText("Incluir");
        jBAdicionar.setName("Novo"); // NOI18N
        jBAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBAdicionarMouseClicked(evt);
            }
        });
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });
        jPBotoes.add(jBAdicionar);

        jBAlterar.setText("Alterar");
        jBAlterar.setName("Alterar"); // NOI18N
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });
        jPBotoes.add(jBAlterar);

        jBExcluir.setText("Excluir");
        jBExcluir.setName("Excluir"); // NOI18N
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });
        jPBotoes.add(jBExcluir);

        jBGravar.setText("Gravar");
        jBGravar.setName("Gravar"); // NOI18N
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });
        jPBotoes.add(jBGravar);

        jBCancelar.setText("Cancelar");
        jBCancelar.setName("Cancelar"); // NOI18N
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPBotoes.add(jBCancelar);

        jLabel19.setText("Nome");

        jLabel20.setText("Comemoração");

        jLabel4.setText("Nome");

        jBAdd.setText("Adicionar");
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jCBcomemoracao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aniversário", "Casamento Cívil", "Casamento Religioso", "Namoro", "Noivado", "Batizado", " " }));

        jLabel6.setText("Tipo Amizade");

        jTFTpAmizade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTpAmizadeActionPerformed(evt);
            }
        });

        jBPesquisar2.setText("Pesquisar");
        jBPesquisar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisar2MouseClicked(evt);
            }
        });
        jBPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisar2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data");

        jTFData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPRelacaoClienteLayout = new javax.swing.GroupLayout(jPRelacaoCliente);
        jPRelacaoCliente.setLayout(jPRelacaoClienteLayout);
        jPRelacaoClienteLayout.setHorizontalGroup(
            jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                        .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                                        .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBPesquisar2)))
                                .addGap(13, 13, 13)
                                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))
                            .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jCBcomemoracao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTFNomerelacao, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jTFTpAmizade, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                                        .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBAdd)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPRelacaoClienteLayout.setVerticalGroup(
            jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPesquisar2))))
                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)))
                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPRelacaoClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)))
                .addGap(7, 7, 7)
                .addGroup(jPRelacaoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFTpAmizade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNomerelacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBcomemoracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPRelacaoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPRelacaoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(655, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAdicionarMouseClicked

    }//GEN-LAST:event_jBAdicionarMouseClicked

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed

        jTFIdPessoa.setText("");
        jTFnome.setText("");
        jTFNomerelacao.setText("");
        jTFTpAmizade.setText("");
        jTFData.setText("");
        jCBcomemoracao.setSelectedIndex(0);
        situacao = 1;
        estadobotoes(true);
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed

    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed

    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed

    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        if (!jTFIdPessoa.getText().equals("")) {
            if (!jTFNomerelacao.getText().equals("")) {
                if (!jTFTpAmizade.getText().equals("")) {
                    IncluirLista();
                } else {
                    JOptionPane.showMessageDialog(null, "Informe o tipo de amizade!");
                    jTFNomerelacao.grabFocus();
                }
            }else {
                    JOptionPane.showMessageDialog(null, "Informe o nome!");
                    jTFNomerelacao.grabFocus();
                }
        }else {
                    JOptionPane.showMessageDialog(null, "Informe o codigo!");
                    jTFNomerelacao.grabFocus();
                }
    }//GEN-LAST:event_jBAddActionPerformed

    private void jBPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPesquisar2ActionPerformed

    private void jBPesquisar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisar2MouseClicked

        final InterfaceRetornaPessoa retornaPessoa = new InterfaceRetornaPessoa();
        retornaPessoa.setVisible(true);
        retornaPessoa.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdPessoa.setText(retornaPessoa.retornaId);
                jTFnome.setText(retornaPessoa.retornaDsPessoa);
            }
        });
    }//GEN-LAST:event_jBPesquisar2MouseClicked

    private void jTFTpAmizadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTpAmizadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTpAmizadeActionPerformed

    private void jTFDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceRelacaoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceRelacaoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceRelacaoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceRelacaoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceRelacaoPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jBPesquisar2;
    private javax.swing.JComboBox<String> jCBcomemoracao;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPBotoes;
    private javax.swing.JPanel jPRelacaoCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFData;
    private javax.swing.JTextField jTFIdPessoa;
    private javax.swing.JTextField jTFNomerelacao;
    private javax.swing.JTextField jTFTpAmizade;
    private javax.swing.JTextField jTFnome;
    private javax.swing.JTable jTrelacao;
    // End of variables declaration//GEN-END:variables
 private void estadobotoes(boolean situacao) {
        jBAdicionar.setEnabled(!situacao);
        jBAlterar.setEnabled(!situacao);
        jBExcluir.setEnabled(!situacao);
        jBGravar.setEnabled(situacao);
        jBCancelar.setEnabled(situacao);
    }
 
 public void IncluirLista() {
        DefaultTableModel ItensFornece = (DefaultTableModel) jTrelacao.getModel();

        int totlinha = jTrelacao.getRowCount();
        int incluir = 0;

        if (incluir == 0) {
            ItensFornece.setNumRows(totlinha + 1);
            ItensFornece.setValueAt(jTFIdPessoa.getText(), totlinha, 0);
            ItensFornece.setValueAt(jTFNomerelacao.getText(), totlinha, 1);
            ItensFornece.setValueAt(jCBcomemoracao.getSelectedItem(), totlinha, 2);
            ItensFornece.setValueAt(jTFData.getText(), totlinha, 3);
            ItensFornece.setValueAt(jTFTpAmizade.getText(), totlinha, 4);

            jTFNomerelacao.setText("");
            jCBcomemoracao.setSelectedIndex(0);
            jTFData.setText("");
            jTFTpAmizade.setText("");
        }
    }
}
