package br.tcc.Interface;

import br.tcc.Validacoes.LimparCampos;
import br.tcc.Validacoes.PreencherJtableGenerico;
import br.tcc.Validacoes.ValidaNumero;
import br.tcc.classe.Funcionario;
import br.tcc.classe.Telefone;
import br.tcc.dao.PessoaDAO;
import br.tcc.dao.TelefoneDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOÃO PAULO
 */
public class InterfaceTelefone extends javax.swing.JFrame {
    
    Telefone telefone = new Telefone();
    TelefoneDAO telefoneDAO = new TelefoneDAO();
    Funcionario funcionario = new Funcionario();
    LimparCampos lcampos = new LimparCampos();
    PessoaDAO pessoaDAO = new PessoaDAO();
    InterfaceFuncionario intFun = new InterfaceFuncionario();
   
    /**
     * Creates new form InterfaceTelefone
     */
    public InterfaceTelefone() {
        
        initComponents();
        jTFIdPessoa.setEnabled(false);
        jTFNome.setEnabled(false);
             
        
              
    }
    public void CapturaIdPessoa(String IdPessoa) throws SQLException{ 
     
        jTFIdPessoa.setText(IdPessoa);
      
    }
    public void capturaFone(String fone) throws SQLException{ 
     
        jTFFone.setText(fone); 
    }
    
    public void capturaDsPessoa(String DsPessoa) throws SQLException{
       
        jTFNome.setText(DsPessoa);
         atualizatabela(WIDTH);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTelefone = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFFone = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone = new javax.swing.text.MaskFormatter("(##) #####-####");

            jTFFone = new javax.swing.JFormattedTextField(telefone);
        }catch(Exception e){
        }
        jBAdicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCBTipo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTelefone = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFIdPessoa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Telefone");

        jLabel1.setText("Telefone");

        jTFFone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFFoneMouseClicked(evt);
            }
        });

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Principal", "Casa", "Celular 1", "Celular 2", "Trabalho", "Recado" }));

        jTTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Numero"
            }
        ));
        jScrollPane1.setViewportView(jTTelefone);

        jLabel3.setText("Nome");

        jLabel4.setText("Código");

        jTFIdPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIdPessoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTelefoneLayout = new javax.swing.GroupLayout(jPTelefone);
        jPTelefone.setLayout(jPTelefoneLayout);
        jPTelefoneLayout.setHorizontalGroup(
            jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .addGroup(jPTelefoneLayout.createSequentialGroup()
                        .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPTelefoneLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jCBTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPTelefoneLayout.createSequentialGroup()
                                .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBAdicionar))))
                    .addGroup(jPTelefoneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNome)))
                .addContainerGap())
        );
        jPTelefoneLayout.setVerticalGroup(
            jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTFIdPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPTelefoneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBAdicionar)
                        .addComponent(jTFFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 506, 398);
    }// </editor-fold>//GEN-END:initComponents

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        Integer idTpFone = null;
        telefone.setIDPESSOA(Integer.parseInt(jTFIdPessoa.getText()));
        telefone.setTPFONE((String) jCBTipo.getSelectedItem());
        telefone.setNRFONE(jTFFone.getText());
        
        if(jTFFone.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o numeno do telefone");
            jTFFone.grabFocus();
            return;
        }
        telefoneDAO.incluir(telefone);
        JOptionPane.showMessageDialog(null, "Telefone Cadastrado com Sucesso!");
        atualizatabela(WIDTH);
        
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jTFFoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFFoneMouseClicked

        ValidaNumero validaNumero = new ValidaNumero();
        validaNumero.ValidaNumero(jTFFone);
    }//GEN-LAST:event_jTFFoneMouseClicked

    private void jTFIdPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIdPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdPessoaActionPerformed

       private void atualizatabela(int idPes){
           PreencherJtableGenerico preencher = new PreencherJtableGenerico();
           idPes = Integer.parseInt(jTFIdPessoa.getText());
           telefoneDAO.consulta(idPes, telefone);
           preencher.PreencherJComboBox(jTTelefone, telefone.getRetorno());
           
           return;
            
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceTelefone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JComboBox jCBTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPTelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFone;
    private javax.swing.JTextField jTFIdPessoa;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTable jTTelefone;
    // End of variables declaration//GEN-END:variables

//    private void validarTabela() {
//        DefaultTableModel modelo = (DefaultTableModel) jTTelefone.getModel();
//        modelo.setNumRows(0);
//        int verifica = 0;
//        
//            for(int linha = 0; linha < jTTelefone.getRowCount(); linha++){
//                verifica = 1;
//                String tipo =(String)jTTelefone.getModel().getValueAt(linha,0); //0=coluna;
//                switch(tipo){
//                    case "0":
//                        tipo = "PRINCIPAL";
//                        break;
//                    case "1":
//                        tipo = "CASA";
//                        break;
//                    case "2":
//                        tipo = "CELULAR 1";
//                        break;
//                    case "3":
//                        tipo = "CELULAR 2";
//                        break;
//                    case "4":
//                        tipo = "TRABALHO";
//                        break;
//                    case "5":
//                        tipo = "RECADO";
//                        break;
//                        
//                }
//                System.out.println(tipo);
//                Object t = tipo;
//                modelo.addColumn(linha, (Object[]) t);    
//            }
//            if (verifica == 0){
//                atualizatabela(WIDTH);
//            }
       
//      }

 
}
