
package br.tcc.Interface;

import br.tcc.ConsultaSimples.ConsultaFamilia;
import br.tcc.ConsultaSimples.ConsultaProduto;
import br.tcc.Validacoes.LimparCampos;
import br.tcc.Validacoes.PreencherJtableGenerico;
import br.tcc.Validacoes.ValidaNumero;
import br.tcc.classe.Composicao;
import br.tcc.classe.Produto;
import br.tcc.dao.ComposicaoDAO;
import br.tcc.dao.ProdutoDAO;
import com.oracle.jrockit.jfr.Producer;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOÃO PAULO
 */
public class InterfaceProduto extends javax.swing.JFrame {

    LimparCampos lcampos = new LimparCampos();
    ValidaNumero validaNumero = new ValidaNumero();
    Produto produto = new Produto();
    ProdutoDAO produtoDAO = new ProdutoDAO();
    Composicao composicao = new Composicao();
    ComposicaoDAO composicaoDAO = new ComposicaoDAO();
    private Integer situacao = 0;
    public String retornaId = "";

    /**
     * Creates new form InterfaceProduto
     */
    public InterfaceProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        TpMateria = new javax.swing.ButtonGroup();
        jTPProduto = new javax.swing.JTabbedPane();
        jPCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFIdProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFTFDtCompra = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFDsProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFIdFamilia = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jTFDsFamilia = new javax.swing.JTextField();
        jPanelbotoes1 = new javax.swing.JPanel();
        jBIncluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBGravar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPComposicao = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTFIdProduto1 = new javax.swing.JTextField();
        jBPesquisar1 = new javax.swing.JButton();
        jTFProduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFQtdProdComp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jBAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTComposicao = new javax.swing.JTable();
        jRBPrima = new javax.swing.JRadioButton();
        jRBFinal = new javax.swing.JRadioButton();
        jPConsulta = new javax.swing.JPanel();
        jCbPesquisa2 = new javax.swing.JComboBox();
        jTFPesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbPesquisa = new javax.swing.JTable();
        jBtPesquisa1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTbProdutoComposto = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");

        jLabel1.setText("Código");

        jLabel5.setText("Data da Compra");

        try {
            jFTFDtCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Tipo de Materia");

        jLabel3.setText("Produto");

        jLabel4.setText("Código da Família");

        jTFIdFamilia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFIdFamiliaFocusLost(evt);
            }
        });

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisarMouseClicked(evt);
            }
        });
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jPanelbotoes1.setBackground(new java.awt.Color(153, 153, 153));

        jBIncluir.setText("Incluir");
        jBIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIncluirActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBGravar.setText("Gravar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbotoes1Layout = new javax.swing.GroupLayout(jPanelbotoes1);
        jPanelbotoes1.setLayout(jPanelbotoes1Layout);
        jPanelbotoes1Layout.setHorizontalGroup(
            jPanelbotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotoes1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jBIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jBCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelbotoes1Layout.setVerticalGroup(
            jPanelbotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbotoes1Layout.createSequentialGroup()
                .addGroup(jPanelbotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelbotoes1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelbotoes1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanelbotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );

        jSeparator1.setName(""); // NOI18N

        jPComposicao.setBorder(javax.swing.BorderFactory.createTitledBorder("Composição"));

        jLabel6.setText("Código Produto");

        jTFIdProduto1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFIdProduto1FocusLost(evt);
            }
        });

        jBPesquisar1.setText("Pesquisar");
        jBPesquisar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBPesquisar1MouseClicked(evt);
            }
        });
        jBPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisar1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Produto");

        jTFQtdProdComp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFQtdProdCompFocusLost(evt);
            }
        });

        jLabel8.setText("Quantidade");

        jBAdicionar.setText("Adicionar");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jTComposicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTComposicao);

        javax.swing.GroupLayout jPComposicaoLayout = new javax.swing.GroupLayout(jPComposicao);
        jPComposicao.setLayout(jPComposicaoLayout);
        jPComposicaoLayout.setHorizontalGroup(
            jPComposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPComposicaoLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(96, 96, 96)
                .addComponent(jLabel7)
                .addGap(193, 193, 193)
                .addComponent(jLabel8))
            .addGroup(jPComposicaoLayout.createSequentialGroup()
                .addComponent(jTFIdProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBPesquisar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFQtdProdComp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAdicionar))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPComposicaoLayout.setVerticalGroup(
            jPComposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPComposicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPComposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPComposicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFIdProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar1)
                    .addComponent(jTFProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFQtdProdComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        TpMateria.add(jRBPrima);
        jRBPrima.setText("Prima");
        jRBPrima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBPrimaMousePressed(evt);
            }
        });

        TpMateria.add(jRBFinal);
        jRBFinal.setText("Final");
        jRBFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBFinalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                        .addComponent(jPComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(jPanelbotoes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jTFIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jFTFDtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addComponent(jRBPrima)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBFinal))))
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jTFIdFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBPesquisar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTFDsFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTFDsProduto)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE))
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTFIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPCadastroLayout.createSequentialGroup()
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRBPrima)
                                    .addComponent(jRBFinal))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(26, 26, 26)))
                            .addGap(2, 2, 2)))
                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jFTFDtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPCadastroLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(26, 26, 26))))
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(254, Short.MAX_VALUE))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDsProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFIdFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPesquisar)
                            .addComponent(jTFDsFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPComposicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelbotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTPProduto.addTab("Cadastro", jPCadastro);

        jCbPesquisa2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Produto" }));

        jTbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Tipo de Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbPesquisa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTbPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbPesquisaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTbPesquisa);

        jBtPesquisa1.setText("Pesquisar");
        jBtPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtPesquisa1ActionPerformed(evt);
            }
        });

        jTbProdutoComposto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbProdutoComposto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTbProdutoComposto);

        javax.swing.GroupLayout jPConsultaLayout = new javax.swing.GroupLayout(jPConsulta);
        jPConsulta.setLayout(jPConsultaLayout);
        jPConsultaLayout.setHorizontalGroup(
            jPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPConsultaLayout.createSequentialGroup()
                            .addComponent(jCbPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtPesquisa1))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPConsultaLayout.setVerticalGroup(
            jPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtPesquisa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTPProduto.addTab("Consulta", jPConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPProduto)
        );

        setSize(new java.awt.Dimension(617, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jBIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIncluirActionPerformed

        jFTFDtCompra.grabFocus();
        lcampos.LimparCampos(jTPProduto);
        situacao = 1;
        estadobotoes(true);
        jRBPrima.setSelected(true);

    }//GEN-LAST:event_jBIncluirActionPerformed

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed

        if (situacao == 1) {

            if (jFTFDtCompra.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe a data de compra do produto");
                jFTFDtCompra.grabFocus();
                return;
            }
            if (jTFDsProduto.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o nome do produto");
                jTFDsProduto.grabFocus();
                return;
            }
            if (jTFIdFamilia.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe a família do produto");
                jTFIdFamilia.grabFocus();
            } else {
                char selecionado;
                if (jRBPrima.isSelected()) {
                    selecionado = 'P';
                } else {
                    selecionado = 'F';
                }
                if (jRBPrima.isSelected()) {
                    produto.setIDFAMILIA(Integer.parseInt(jTFIdFamilia.getText()));
                    produto.setDSPRODUTO(jTFDsProduto.getText().toUpperCase());
                    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                    java.sql.Date data = null;
                    try {
                        data = new java.sql.Date(format.parse(jFTFDtCompra.getText().toString()).getTime());
                    } catch (ParseException ex) {
                        Logger.getLogger(InterfaceProduto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    produto.setDTCOMRPA(data.toString());

                    produto.setTPMATERIA(selecionado);
                    produtoDAO.incluir(produto);
                    lcampos.LimparCampos(jPCadastro);
                    estadobotoes(false);
                } else {
                    produto.setIDFAMILIA(Integer.parseInt(jTFIdFamilia.getText()));
                    produto.setDSPRODUTO(jTFDsProduto.getText().toUpperCase());
                    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                    java.sql.Date data = null;
                    try {
                        data = new java.sql.Date(format.parse(jFTFDtCompra.getText().toString()).getTime());
                    } catch (ParseException ex) {
                        Logger.getLogger(InterfaceProduto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    produto.setDTCOMRPA(data.toString());
                    produto.setTPMATERIA(selecionado);
                    produtoDAO.incluir(produto);

                    Integer idP = null;
                    try {
                       idP = produtoDAO.retornaUltimoId(idP);
                    } catch (SQLException ex) {
                        Logger.getLogger(InterfaceProduto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                       
                    int totlinha = jTComposicao.getRowCount();
                    int conta = 0;
                    for (int i = 1; i <= totlinha; i++) {
                        String IdProd = (String) jTComposicao.getValueAt(conta, 0);
                        String QtdProd = (String) jTComposicao.getValueAt(conta, 2);
                        composicao.setIDPRODUTO(idP);
                        composicao.setIDPROD(Integer.parseInt(IdProd));
                        composicao.setQTDPRODUTO(Double.parseDouble(QtdProd));                       
                        conta = conta + 1;
                        composicaoDAO.incluir(composicao);
                    }
                     lcampos.LimparCampos(jPCadastro);
                }
            }
        }
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPesquisar1ActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed

        situacao = 2;
        estadobotoes(true);
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed

        situacao = 1;
        estadobotoes(true);
        int t = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente EXCLUIR o registro?");
        if (t == 0) {
            composicaoDAO.excluir(composicao);
            produtoDAO.excluir(produto);
        }
        lcampos.LimparCampos(jPCadastro);
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed

        DefaultTableModel TabComposicao = (DefaultTableModel) jTComposicao.getModel();

        composicao.setIDPROD(Integer.parseInt(jTFIdProduto1.getText()));

        int totlinha = jTComposicao.getRowCount();
        int alterar = 0;
        int conta = 0;
        int linha = 0;

        for (int i = 1; i <= totlinha; i++) {
            String IdProd = (String) jTComposicao.getValueAt(conta, 1);

            if (jTFIdProduto1.getText().equals(IdProd)) {
                int opcao_escolhida = JOptionPane.showConfirmDialog(null, "Produto ja"
                        + " cadastrado, deseja alterar quantidade e valor", "Alteração ",
                        JOptionPane.YES_NO_OPTION);

                if (opcao_escolhida == JOptionPane.YES_OPTION) {
                    alterar = 1;
                    linha = conta;
                } else {
                    return;
                }
            }
            conta = conta + 1;
        }
        if (alterar == 0) {
            //Adcionar na lista
            TabComposicao.setNumRows(totlinha + 1);
            TabComposicao.setValueAt((jTFIdProduto1.getText()), totlinha, 0);
            TabComposicao.setValueAt((jTFProduto.getText()), totlinha, 1);
            TabComposicao.setValueAt((jTFQtdProdComp.getText()), totlinha, 2);

            jTFIdProduto1.setText("");
            jTFProduto.setText("");
            jTFQtdProdComp.setText("");

        } else if (alterar == 1) {
            //caso for alteração

            String qtde = (String) jTComposicao.getValueAt(linha, 2);
            double total = Double.parseDouble(qtde) + Double.parseDouble(jTFQtdProdComp.getText());
            TabComposicao.setValueAt(total, linha, 2);

            jTFIdProduto1.setText("");
            jTFDsProduto.setText("");
            jTFQtdProdComp.setText("");

        }

    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisarMouseClicked

        final ConsultaFamilia retornaFamilia = new ConsultaFamilia();
        retornaFamilia.setVisible(true);
        retornaFamilia.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdFamilia.setText(retornaFamilia.retornaId);
                jTFDsFamilia.setText(retornaFamilia.retornaDsFamilia);
            }
        });
    }//GEN-LAST:event_jBPesquisarMouseClicked

    private void jBPesquisar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBPesquisar1MouseClicked

        final ConsultaProduto retornaProduto = new ConsultaProduto();
        retornaProduto.setVisible(true);
        retornaProduto.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTFIdProduto1.setText(retornaProduto.retornaId);
                jTFProduto.setText(retornaProduto.retornaDsProduto);
            }
        });
    }//GEN-LAST:event_jBPesquisar1MouseClicked

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed

         int t = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente cancelar o cadastro?");
        if (t == 0) {
            situacao = 2;
            lcampos.LimparCampos(jPCadastro);
            estadobotoes(false);
        }
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTFIdFamiliaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFIdFamiliaFocusLost

        validaNumero.ValidaNumero(jTFIdFamilia);
    }//GEN-LAST:event_jTFIdFamiliaFocusLost

    private void jTFIdProduto1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFIdProduto1FocusLost

        validaNumero.ValidaNumero(jTFIdProduto1);
    }//GEN-LAST:event_jTFIdProduto1FocusLost

    private void jTFQtdProdCompFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFQtdProdCompFocusLost

        validaNumero.ValidaNumero(jTFQtdProdComp);
    }//GEN-LAST:event_jTFQtdProdCompFocusLost

    private void jRBPrimaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBPrimaMousePressed

        jTFDsProduto.setEnabled(true);
        jFTFDtCompra.setEnabled(true);
        jTFIdFamilia.setEnabled(true);

        jTFDsFamilia.setEnabled(false);
        jTFIdProduto1.setEnabled(false);
        jTFProduto.setEnabled(false);
        jTFQtdProdComp.setEnabled(false);
      
        jBAdicionar.setEnabled(true);
        jBPesquisar.setEnabled(false);
        jBPesquisar1.setEnabled(false);
        jTComposicao.setEnabled(false);
    }//GEN-LAST:event_jRBPrimaMousePressed

    private void jRBFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBFinalMouseClicked

        jTFDsProduto.setEnabled(true);
        jFTFDtCompra.setEnabled(true);
        jTFIdFamilia.setEnabled(true);

        jTFDsFamilia.setEnabled(false);
        jTFIdProduto1.setEnabled(true);
        jTFProduto.setEnabled(false);
        jTFQtdProdComp.setEnabled(true);
        
        jBAdicionar.setEnabled(true);
        jBPesquisar.setEnabled(true);
        jBPesquisar1.setEnabled(true);
        jTComposicao.setEnabled(true);
    }//GEN-LAST:event_jRBFinalMouseClicked

    private void jBtPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtPesquisa1ActionPerformed

        PreencherJtableGenerico preencher = new PreencherJtableGenerico();
        switch (jCbPesquisa2.getSelectedIndex()) {
            case 0: {
                produtoDAO.consulta(produto);
                preencher.PreencherJComboBox(jTbPesquisa, produto.getRetorno());
                return;
            }
            case 1: {
                produto.setDSPRODUTO(jTFPesquisa.getText().toUpperCase());
                produtoDAO.consultadescricao(produto);
                preencher.PreencherJComboBox(jTbPesquisa, produto.getRetorno());
                return;
            }
        }
    }//GEN-LAST:event_jBtPesquisa1ActionPerformed

    private void jTbPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbPesquisaMouseClicked
        
        PreencherJtableGenerico preencher = new PreencherJtableGenerico();

        int linha = jTbPesquisa.getSelectedRow();
        retornaId = jTbPesquisa.getValueAt(linha, 0).toString();
        Integer idproduto = Integer.parseInt(retornaId);

        composicaoDAO.consultaComposicao(composicao, idproduto);
        
        preencher.PreencherJtableGenerico(jTbProdutoComposto, composicao.getRetorno());
    }//GEN-LAST:event_jTbPesquisaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup TpMateria;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jBIncluir;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JButton jBPesquisar1;
    private javax.swing.JButton jBtPesquisa1;
    private javax.swing.JComboBox jCbPesquisa2;
    private javax.swing.JFormattedTextField jFTFDtCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPComposicao;
    private javax.swing.JPanel jPConsulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelbotoes1;
    private javax.swing.JRadioButton jRBFinal;
    private javax.swing.JRadioButton jRBPrima;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTComposicao;
    private javax.swing.JTextField jTFDsFamilia;
    private javax.swing.JTextField jTFDsProduto;
    private javax.swing.JTextField jTFIdFamilia;
    private javax.swing.JTextField jTFIdProduto;
    private javax.swing.JTextField jTFIdProduto1;
    private javax.swing.JTextField jTFPesquisa;
    private javax.swing.JTextField jTFProduto;
    private javax.swing.JTextField jTFQtdProdComp;
    private javax.swing.JTabbedPane jTPProduto;
    private javax.swing.JTable jTbPesquisa;
    private javax.swing.JTable jTbProdutoComposto;
    // End of variables declaration//GEN-END:variables

    private void estadobotoes(boolean situacao) {
        jBIncluir.setEnabled(!situacao);
        jBAlterar.setEnabled(!situacao);
        jBExcluir.setEnabled(!situacao);
        jBGravar.setEnabled(situacao);
        jBCancelar.setEnabled(situacao);
    }
}
